//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientPortal.Data.Contexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class CallDailySummary
    {
        public int SearchCampaignId { get; set; }
        public System.DateTime Date { get; set; }
        public int Calls { get; set; }
    
        public virtual SearchCampaign SearchCampaign { get; set; }
    }
}
