//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientPortal.Data.Contexts
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ClientPortalDWContext : DbContext
    {
        public ClientPortalDWContext()
            : base("name=ClientPortalDWContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DimCountry> DimCountries { get; set; }
        public virtual DbSet<DimRegion> DimRegions { get; set; }
        public virtual DbSet<FactClick> FactClicks { get; set; }
        public virtual DbSet<DimDate> DimDates { get; set; }
        public virtual DbSet<DimAdvertiser> DimAdvertisers { get; set; }
        public virtual DbSet<DimAffiliate> DimAffiliates { get; set; }
        public virtual DbSet<DimOffer> DimOffers { get; set; }
        public virtual DbSet<DimBrowser> DimBrowsers { get; set; }
        public virtual DbSet<DimDevice> DimDevices { get; set; }
        public virtual DbSet<FactConversion> FactConversions { get; set; }
    
        public virtual ObjectResult<DeviceClicks> ClicksByDevice(Nullable<int> advertiserId, Nullable<System.DateTime> date1, Nullable<System.DateTime> date2)
        {
            var advertiserIdParameter = advertiserId.HasValue ?
                new ObjectParameter("advertiserId", advertiserId) :
                new ObjectParameter("advertiserId", typeof(int));
    
            var date1Parameter = date1.HasValue ?
                new ObjectParameter("date1", date1) :
                new ObjectParameter("date1", typeof(System.DateTime));
    
            var date2Parameter = date2.HasValue ?
                new ObjectParameter("date2", date2) :
                new ObjectParameter("date2", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DeviceClicks>("ClicksByDevice", advertiserIdParameter, date1Parameter, date2Parameter);
        }
    
        public virtual ObjectResult<ConversionsByRegion> ConversionsByRegion(Nullable<int> advertiserId, Nullable<System.DateTime> date1, Nullable<System.DateTime> date2)
        {
            var advertiserIdParameter = advertiserId.HasValue ?
                new ObjectParameter("advertiserId", advertiserId) :
                new ObjectParameter("advertiserId", typeof(int));
    
            var date1Parameter = date1.HasValue ?
                new ObjectParameter("date1", date1) :
                new ObjectParameter("date1", typeof(System.DateTime));
    
            var date2Parameter = date2.HasValue ?
                new ObjectParameter("date2", date2) :
                new ObjectParameter("date2", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ConversionsByRegion>("ConversionsByRegion", advertiserIdParameter, date1Parameter, date2Parameter);
        }
    }
}
