//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientPortal.Data.Contexts
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ClientPortalContext : DbContext
    {
        public ClientPortalContext()
            : base("name=ClientPortalContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ConversionData> ConversionDatas { get; set; }
        public virtual DbSet<Goal> Goals { get; set; }
        public virtual DbSet<AdvertiserContact> AdvertiserContacts { get; set; }
        public virtual DbSet<Contact> Contacts { get; set; }
        public virtual DbSet<FileUpload> FileUploads { get; set; }
        public virtual DbSet<Metric> Metrics { get; set; }
        public virtual DbSet<MetricCount> MetricCounts { get; set; }
        public virtual DbSet<MetricValue> MetricValues { get; set; }
        public virtual DbSet<SearchDailySummary> SearchDailySummaries { get; set; }
        public virtual DbSet<Conversion> Conversions { get; set; }
        public virtual DbSet<SearchCampaign> SearchCampaigns { get; set; }
        public virtual DbSet<UserProfile> UserProfiles { get; set; }
        public virtual DbSet<SearchDailySummary2> SearchDailySummary2 { get; set; }
        public virtual DbSet<Advertiser> Advertisers { get; set; }
        public virtual DbSet<GoogleAnalyticsSummary> GoogleAnalyticsSummaries { get; set; }
        public virtual DbSet<SearchAccount> SearchAccounts { get; set; }
        public virtual DbSet<SearchChannel> SearchChannels { get; set; }
        public virtual DbSet<UserEvent> UserEvents { get; set; }
        public virtual DbSet<Offer> Offers { get; set; }
        public virtual DbSet<Affiliate> Affiliates { get; set; }
        public virtual DbSet<Campaign> Campaigns { get; set; }
        public virtual DbSet<CampaignDrop> CampaignDrops { get; set; }
        public virtual DbSet<Creative> Creatives { get; set; }
        public virtual DbSet<CreativeType> CreativeTypes { get; set; }
        public virtual DbSet<CreativeSummary> CreativeSummaries { get; set; }
        public virtual DbSet<CreativeStat> CreativeStats { get; set; }
        public virtual DbSet<CakeContact> CakeContacts { get; set; }
        public virtual DbSet<CakeRole> CakeRoles { get; set; }
        public virtual DbSet<CreativeFile> CreativeFiles { get; set; }
        public virtual DbSet<CPMReport> CPMReports { get; set; }
        public virtual DbSet<OfferDailySummary> OfferDailySummaries { get; set; }
        public virtual DbSet<DailySummary> DailySummaries { get; set; }
        public virtual DbSet<SearchProfile> SearchProfiles { get; set; }
        public virtual DbSet<SearchProfileContact> SearchProfileContacts { get; set; }
        public virtual DbSet<SimpleReport> SimpleReports { get; set; }
        public virtual DbSet<CallDailySummary> CallDailySummaries { get; set; }
        public virtual DbSet<Currency> Currencies { get; set; }
        public virtual DbSet<CurrencyConversion> CurrencyConversions { get; set; }
        public virtual DbSet<ClientInfo> ClientInfos { get; set; }
        public virtual DbSet<SearchConvSummary> SearchConvSummaries { get; set; }
        public virtual DbSet<SearchConvType> SearchConvTypes { get; set; }
    }
}
