//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientPortal.Data.Contexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class Conversion
    {
        public string conversion_id { get; set; }
        public System.DateTime conversion_date { get; set; }
        public int affiliate_id { get; set; }
        public int advertiser_id { get; set; }
        public int offer_id { get; set; }
        public byte received_currency_id { get; set; }
        public decimal received_amount { get; set; }
        public string transaction_id { get; set; }
    }
}
