//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientPortal.Data.Contexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class CPMReport
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CPMReport()
        {
            this.ShowConversions = true;
            this.CampaignDrops = new HashSet<CampaignDrop>();
        }
    
        public int CPMReportId { get; set; }
        public int OfferId { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> DateSent { get; set; }
        public string Recipient { get; set; }
        public string RecipientCC { get; set; }
        public string Summary { get; set; }
        public string Conclusion { get; set; }
        public bool ShowConversions { get; set; }
        public bool ShowExtras { get; set; }
        public string ExtraColumnName { get; set; }
        public string ExtraColumnValue { get; set; }
    
        public virtual Offer Offer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CampaignDrop> CampaignDrops { get; set; }
    }
}
