//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientPortal.Data.Contexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class Creative
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Creative()
        {
            this.CreativeStats = new HashSet<CreativeStat>();
            this.CreativeFiles = new HashSet<CreativeFile>();
        }
    
        public int CreativeId { get; set; }
        public int OfferId { get; set; }
        public int CreativeTypeId { get; set; }
        public string CreativeName { get; set; }
        public System.DateTime DateCreated { get; set; }
        public int CreativeStatusId { get; set; }
        public string OfferLinkOverride { get; set; }
        public Nullable<int> Width { get; set; }
        public Nullable<int> Height { get; set; }
        public byte[] Thumbnail { get; set; }
    
        public virtual CreativeType CreativeType { get; set; }
        public virtual Offer Offer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CreativeStat> CreativeStats { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CreativeFile> CreativeFiles { get; set; }
    }
}
