//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientPortal.Data.Contexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class CreativeFile
    {
        public int CreativeFileId { get; set; }
        public int CreativeId { get; set; }
        public string CreativeFileName { get; set; }
        public string CreativeFileLink { get; set; }
        public bool Preview { get; set; }
        public System.DateTime DateCreated { get; set; }
    
        public virtual Creative Creative { get; set; }
    }
}
