//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientPortal.Data.Contexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class DimDate
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DimDate()
        {
            this.FactClicks = new HashSet<FactClick>();
            this.FactConversions = new HashSet<FactConversion>();
            this.FactConversions1 = new HashSet<FactConversion>();
        }
    
        public System.DateTime PK_Date { get; set; }
        public string Date_Name { get; set; }
        public Nullable<System.DateTime> Year { get; set; }
        public string Year_Name { get; set; }
        public Nullable<System.DateTime> Month { get; set; }
        public string Month_Name { get; set; }
        public Nullable<int> Day_Of_Year { get; set; }
        public string Day_Of_Year_Name { get; set; }
        public Nullable<int> Day_Of_Month { get; set; }
        public string Day_Of_Month_Name { get; set; }
        public Nullable<int> Month_Of_Year { get; set; }
        public string Month_Of_Year_Name { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactClick> FactClicks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactConversion> FactConversions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactConversion> FactConversions1 { get; set; }
    }
}
