//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientPortal.Data.Contexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class FactClick
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FactClick()
        {
            this.FactConversions = new HashSet<FactConversion>();
        }
    
        public int ClickKey { get; set; }
        public int RegionKey { get; set; }
        public int CountryKey { get; set; }
        public System.DateTime DateKey { get; set; }
        public int AdvertiserKey { get; set; }
        public int OfferKey { get; set; }
        public int AffiliateKey { get; set; }
        public int BrowserKey { get; set; }
        public int DeviceKey { get; set; }
    
        public virtual DimCountry DimCountry { get; set; }
        public virtual DimRegion DimRegion { get; set; }
        public virtual DimDate DimDate { get; set; }
        public virtual DimAdvertiser DimAdvertiser { get; set; }
        public virtual DimAffiliate DimAffiliate { get; set; }
        public virtual DimOffer DimOffer { get; set; }
        public virtual DimBrowser DimBrowser { get; set; }
        public virtual DimDevice DimDevice { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactConversion> FactConversions { get; set; }
    }
}
