//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientPortal.Data.Contexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class FactConversion
    {
        public string ConversionKey { get; set; }
        public Nullable<int> ClickKey { get; set; }
        public System.DateTime DateKey { get; set; }
        public Nullable<System.DateTime> ClickDateKey { get; set; }
    
        public virtual DimDate DimDate { get; set; }
        public virtual DimDate DimDate1 { get; set; }
        public virtual FactClick FactClick { get; set; }
    }
}
