//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientPortal.Data.Contexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class Goal
    {
        public int Id { get; set; }
        public int AdvertiserId { get; set; }
        public Nullable<int> OfferId { get; set; }
        public string Name { get; set; }
        public GoalType TypeId { get; set; }
        public GoalMetric MetricId { get; set; }
        public decimal Target { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
    
        public virtual Advertiser Advertiser { get; set; }
        public virtual Offer Offer { get; set; }
    }
}
