//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientPortal.Data.Contexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class MetricCount
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MetricCount()
        {
            this.count = 0;
        }
    
        public int offer_id { get; set; }
        public System.DateTime date { get; set; }
        public bool conversions_only { get; set; }
        public int metricvalue_id { get; set; }
        public int count { get; set; }
    
        public virtual MetricValue MetricValue { get; set; }
    }
}
