//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientPortal.Data.Contexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class OfferDailySummary
    {
        public int offer_id { get; set; }
        public System.DateTime date { get; set; }
        public int views { get; set; }
        public int clicks { get; set; }
        public decimal click_thru { get; set; }
        public int conversions { get; set; }
        public int paid { get; set; }
        public int sellable { get; set; }
        public decimal conversion_rate { get; set; }
        public decimal cpl { get; set; }
        public decimal cost { get; set; }
        public decimal rpt { get; set; }
        public decimal revenue { get; set; }
        public decimal margin { get; set; }
        public decimal profit { get; set; }
        public decimal epc { get; set; }
    }
}
