//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientPortal.Data.Contexts
{
    using System;
    
    public enum ReportType : int
    {
        OfferSummary = 1,
        DailySummary = 2,
        ConversionReport = 3,
        Affiliates = 4
    }
}
