//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientPortal.Data.Contexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class SearchAccount
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SearchAccount()
        {
            this.SearchCampaigns = new HashSet<SearchCampaign>();
            this.AltSearchCampaigns = new HashSet<SearchCampaign>();
        }
    
        public int SearchAccountId { get; set; }
        public Nullable<int> AdvertiserId { get; set; }
        public string Name { get; set; }
        public string Channel { get; set; }
        public string AccountCode { get; set; }
        public string ExternalId { get; set; }
        public Nullable<int> SearchProfileId { get; set; }
        public Nullable<decimal> RevPerOrder { get; set; }
        public Nullable<System.DateTime> MinSynchDate { get; set; }
    
        public virtual Advertiser Advertiser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SearchCampaign> SearchCampaigns { get; set; }
        public virtual SearchProfile SearchProfile { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SearchCampaign> AltSearchCampaigns { get; set; }
    }
}
