//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientPortal.Data.Contexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class SearchChannel
    {
        public int SearchChannelId { get; set; }
        public string Prefix { get; set; }
        public string Name { get; set; }
        public string Device { get; set; }
    }
}
