//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientPortal.Data.Contexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class SearchDailySummary2
    {
        public int SearchCampaignId { get; set; }
        public System.DateTime Date { get; set; }
        public decimal Revenue { get; set; }
        public decimal Cost { get; set; }
        public int Orders { get; set; }
        public int Clicks { get; set; }
        public int Impressions { get; set; }
        public int CurrencyId { get; set; }
        public string Network { get; set; }
        public string Device { get; set; }
        public string ClickType { get; set; }
    
        public virtual SearchCampaign SearchCampaign { get; set; }
    }
}
