//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientPortal.Data.Contexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class SimpleReport
    {
        public int SimpleReportId { get; set; }
        public Nullable<int> AdvertiserId { get; set; }
        public Nullable<int> SearchProfileId { get; set; }
        public bool Enabled { get; set; }
        public string Email { get; set; }
        public string EmailCC { get; set; }
        public Nullable<System.DateTime> NextSend { get; set; }
        public int PeriodDays { get; set; }
        public int PeriodMonths { get; set; }
        public Nullable<System.DateTime> LastSend { get; set; }
        public Nullable<System.DateTime> LastStatsDate { get; set; }
    
        public virtual Advertiser Advertiser { get; set; }
        public virtual SearchProfile SearchProfile { get; set; }
    }
}
