//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BingAds.CampaignManagement {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Campaign", Namespace="https://adcenter.microsoft.com/v8")]
    [System.SerializableAttribute()]
    public partial class Campaign : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<BingAds.CampaignManagement.BudgetLimitType> BudgetTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> ConversionTrackingEnabledField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> DailyBudgetField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> DaylightSavingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> MonthlyBudgetField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<BingAds.CampaignManagement.CampaignStatus> StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TimeZoneField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<BingAds.CampaignManagement.BudgetLimitType> BudgetType {
            get {
                return this.BudgetTypeField;
            }
            set {
                if ((this.BudgetTypeField.Equals(value) != true)) {
                    this.BudgetTypeField = value;
                    this.RaisePropertyChanged("BudgetType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> ConversionTrackingEnabled {
            get {
                return this.ConversionTrackingEnabledField;
            }
            set {
                if ((this.ConversionTrackingEnabledField.Equals(value) != true)) {
                    this.ConversionTrackingEnabledField = value;
                    this.RaisePropertyChanged("ConversionTrackingEnabled");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> DailyBudget {
            get {
                return this.DailyBudgetField;
            }
            set {
                if ((this.DailyBudgetField.Equals(value) != true)) {
                    this.DailyBudgetField = value;
                    this.RaisePropertyChanged("DailyBudget");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> DaylightSaving {
            get {
                return this.DaylightSavingField;
            }
            set {
                if ((this.DaylightSavingField.Equals(value) != true)) {
                    this.DaylightSavingField = value;
                    this.RaisePropertyChanged("DaylightSaving");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> MonthlyBudget {
            get {
                return this.MonthlyBudgetField;
            }
            set {
                if ((this.MonthlyBudgetField.Equals(value) != true)) {
                    this.MonthlyBudgetField = value;
                    this.RaisePropertyChanged("MonthlyBudget");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<BingAds.CampaignManagement.CampaignStatus> Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TimeZone {
            get {
                return this.TimeZoneField;
            }
            set {
                if ((object.ReferenceEquals(this.TimeZoneField, value) != true)) {
                    this.TimeZoneField = value;
                    this.RaisePropertyChanged("TimeZone");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BudgetLimitType", Namespace="https://adcenter.microsoft.com/v8")]
    public enum BudgetLimitType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MonthlyBudgetSpendUntilDepleted = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DailyBudgetAccelerated = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DailyBudgetStandard = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CampaignStatus", Namespace="https://adcenter.microsoft.com/v8")]
    public enum CampaignStatus : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Active = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Paused = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BudgetPaused = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BudgetAndManualPaused = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Deleted = 4,
    }
}
