// <auto-generated />
namespace DirectAgents.Domain.MigrationsAB
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Mig_AcctPayInvCamp : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Mig_AcctPayInvCamp));
        
        string IMigrationMetadata.Id
        {
            get { return "201702092133451_Mig_AcctPayInvCamp"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
