//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("CakeModel", "FK_CakeOfferCakeCampaign", "CakeOffer", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Cake.Model.CakeOffer), "CakeCampaign", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Cake.Model.CakeCampaign), true)]
[assembly: EdmRelationshipAttribute("CakeModel", "FK_CakeConversions_CakeCampaigns", "CakeCampaign", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Cake.Model.CakeCampaign), "CakeConversion", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Cake.Model.CakeConversion), true)]

#endregion

namespace Cake.Model
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class CakeEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new CakeEntities object using the connection string found in the 'CakeEntities' section of the application configuration file.
        /// </summary>
        public CakeEntities() : base("name=CakeEntities", "CakeEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new CakeEntities object.
        /// </summary>
        public CakeEntities(string connectionString) : base(connectionString, "CakeEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new CakeEntities object.
        /// </summary>
        public CakeEntities(EntityConnection connection) : base(connection, "CakeEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<CakeAdvertiser> CakeAdvertisers
        {
            get
            {
                if ((_CakeAdvertisers == null))
                {
                    _CakeAdvertisers = base.CreateObjectSet<CakeAdvertiser>("CakeAdvertisers");
                }
                return _CakeAdvertisers;
            }
        }
        private ObjectSet<CakeAdvertiser> _CakeAdvertisers;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<CakeAffiliate> CakeAffiliates
        {
            get
            {
                if ((_CakeAffiliates == null))
                {
                    _CakeAffiliates = base.CreateObjectSet<CakeAffiliate>("CakeAffiliates");
                }
                return _CakeAffiliates;
            }
        }
        private ObjectSet<CakeAffiliate> _CakeAffiliates;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<CakeConversion> CakeConversions
        {
            get
            {
                if ((_CakeConversions == null))
                {
                    _CakeConversions = base.CreateObjectSet<CakeConversion>("CakeConversions");
                }
                return _CakeConversions;
            }
        }
        private ObjectSet<CakeConversion> _CakeConversions;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<CakeOffer> CakeOffers
        {
            get
            {
                if ((_CakeOffers == null))
                {
                    _CakeOffers = base.CreateObjectSet<CakeOffer>("CakeOffers");
                }
                return _CakeOffers;
            }
        }
        private ObjectSet<CakeOffer> _CakeOffers;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<CakeContact> CakeContacts
        {
            get
            {
                if ((_CakeContacts == null))
                {
                    _CakeContacts = base.CreateObjectSet<CakeContact>("CakeContacts");
                }
                return _CakeContacts;
            }
        }
        private ObjectSet<CakeContact> _CakeContacts;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<CakeCampaign> CakeCampaigns
        {
            get
            {
                if ((_CakeCampaigns == null))
                {
                    _CakeCampaigns = base.CreateObjectSet<CakeCampaign>("CakeCampaigns");
                }
                return _CakeCampaigns;
            }
        }
        private ObjectSet<CakeCampaign> _CakeCampaigns;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<CakeUtilityError> CakeUtilityErrors
        {
            get
            {
                if ((_CakeUtilityErrors == null))
                {
                    _CakeUtilityErrors = base.CreateObjectSet<CakeUtilityError>("CakeUtilityErrors");
                }
                return _CakeUtilityErrors;
            }
        }
        private ObjectSet<CakeUtilityError> _CakeUtilityErrors;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the CakeAdvertisers EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCakeAdvertisers(CakeAdvertiser cakeAdvertiser)
        {
            base.AddObject("CakeAdvertisers", cakeAdvertiser);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the CakeAffiliates EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCakeAffiliates(CakeAffiliate cakeAffiliate)
        {
            base.AddObject("CakeAffiliates", cakeAffiliate);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the CakeConversions EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCakeConversions(CakeConversion cakeConversion)
        {
            base.AddObject("CakeConversions", cakeConversion);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the CakeOffers EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCakeOffers(CakeOffer cakeOffer)
        {
            base.AddObject("CakeOffers", cakeOffer);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the CakeContacts EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCakeContacts(CakeContact cakeContact)
        {
            base.AddObject("CakeContacts", cakeContact);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the CakeCampaigns EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCakeCampaigns(CakeCampaign cakeCampaign)
        {
            base.AddObject("CakeCampaigns", cakeCampaign);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the CakeUtilityErrors EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCakeUtilityErrors(CakeUtilityError cakeUtilityError)
        {
            base.AddObject("CakeUtilityErrors", cakeUtilityError);
        }

        #endregion
        #region Function Imports
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public int ResetTables()
        {
            return base.ExecuteFunction("ResetTables");
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CakeModel", Name="CakeAdvertiser")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CakeAdvertiser : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new CakeAdvertiser object.
        /// </summary>
        /// <param name="advertiser_Id">Initial value of the Advertiser_Id property.</param>
        public static CakeAdvertiser CreateCakeAdvertiser(global::System.Int32 advertiser_Id)
        {
            CakeAdvertiser cakeAdvertiser = new CakeAdvertiser();
            cakeAdvertiser.Advertiser_Id = advertiser_Id;
            return cakeAdvertiser;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Advertiser_Id
        {
            get
            {
                return _Advertiser_Id;
            }
            set
            {
                if (_Advertiser_Id != value)
                {
                    OnAdvertiser_IdChanging(value);
                    ReportPropertyChanging("Advertiser_Id");
                    _Advertiser_Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Advertiser_Id");
                    OnAdvertiser_IdChanged();
                }
            }
        }
        private global::System.Int32 _Advertiser_Id;
        partial void OnAdvertiser_IdChanging(global::System.Int32 value);
        partial void OnAdvertiser_IdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String AdvertiserName
        {
            get
            {
                return _AdvertiserName;
            }
            set
            {
                OnAdvertiserNameChanging(value);
                ReportPropertyChanging("AdvertiserName");
                _AdvertiserName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("AdvertiserName");
                OnAdvertiserNameChanged();
            }
        }
        private global::System.String _AdvertiserName;
        partial void OnAdvertiserNameChanging(global::System.String value);
        partial void OnAdvertiserNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> AccountManager_Id
        {
            get
            {
                return _AccountManager_Id;
            }
            set
            {
                OnAccountManager_IdChanging(value);
                ReportPropertyChanging("AccountManager_Id");
                _AccountManager_Id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AccountManager_Id");
                OnAccountManager_IdChanged();
            }
        }
        private Nullable<global::System.Int32> _AccountManager_Id;
        partial void OnAccountManager_IdChanging(Nullable<global::System.Int32> value);
        partial void OnAccountManager_IdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String AccountManagerName
        {
            get
            {
                return _AccountManagerName;
            }
            set
            {
                OnAccountManagerNameChanging(value);
                ReportPropertyChanging("AccountManagerName");
                _AccountManagerName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("AccountManagerName");
                OnAccountManagerNameChanged();
            }
        }
        private global::System.String _AccountManagerName;
        partial void OnAccountManagerNameChanging(global::System.String value);
        partial void OnAccountManagerNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String AdManagerName
        {
            get
            {
                return _AdManagerName;
            }
            set
            {
                OnAdManagerNameChanging(value);
                ReportPropertyChanging("AdManagerName");
                _AdManagerName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("AdManagerName");
                OnAdManagerNameChanged();
            }
        }
        private global::System.String _AdManagerName;
        partial void OnAdManagerNameChanging(global::System.String value);
        partial void OnAdManagerNameChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CakeModel", Name="CakeAffiliate")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CakeAffiliate : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new CakeAffiliate object.
        /// </summary>
        /// <param name="affiliate_Id">Initial value of the Affiliate_Id property.</param>
        public static CakeAffiliate CreateCakeAffiliate(global::System.Int32 affiliate_Id)
        {
            CakeAffiliate cakeAffiliate = new CakeAffiliate();
            cakeAffiliate.Affiliate_Id = affiliate_Id;
            return cakeAffiliate;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Affiliate_Id
        {
            get
            {
                return _Affiliate_Id;
            }
            set
            {
                if (_Affiliate_Id != value)
                {
                    OnAffiliate_IdChanging(value);
                    ReportPropertyChanging("Affiliate_Id");
                    _Affiliate_Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Affiliate_Id");
                    OnAffiliate_IdChanged();
                }
            }
        }
        private global::System.Int32 _Affiliate_Id;
        partial void OnAffiliate_IdChanging(global::System.Int32 value);
        partial void OnAffiliate_IdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String AffiliateName
        {
            get
            {
                return _AffiliateName;
            }
            set
            {
                OnAffiliateNameChanging(value);
                ReportPropertyChanging("AffiliateName");
                _AffiliateName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("AffiliateName");
                OnAffiliateNameChanged();
            }
        }
        private global::System.String _AffiliateName;
        partial void OnAffiliateNameChanging(global::System.String value);
        partial void OnAffiliateNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> AccountManager_Id
        {
            get
            {
                return _AccountManager_Id;
            }
            set
            {
                OnAccountManager_IdChanging(value);
                ReportPropertyChanging("AccountManager_Id");
                _AccountManager_Id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AccountManager_Id");
                OnAccountManager_IdChanged();
            }
        }
        private Nullable<global::System.Int32> _AccountManager_Id;
        partial void OnAccountManager_IdChanging(Nullable<global::System.Int32> value);
        partial void OnAccountManager_IdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String StatusName
        {
            get
            {
                return _StatusName;
            }
            set
            {
                OnStatusNameChanging(value);
                ReportPropertyChanging("StatusName");
                _StatusName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("StatusName");
                OnStatusNameChanged();
            }
        }
        private global::System.String _StatusName;
        partial void OnStatusNameChanging(global::System.String value);
        partial void OnStatusNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Website
        {
            get
            {
                return _Website;
            }
            set
            {
                OnWebsiteChanging(value);
                ReportPropertyChanging("Website");
                _Website = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Website");
                OnWebsiteChanged();
            }
        }
        private global::System.String _Website;
        partial void OnWebsiteChanging(global::System.String value);
        partial void OnWebsiteChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String AccountManagerName
        {
            get
            {
                return _AccountManagerName;
            }
            set
            {
                OnAccountManagerNameChanging(value);
                ReportPropertyChanging("AccountManagerName");
                _AccountManagerName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("AccountManagerName");
                OnAccountManagerNameChanged();
            }
        }
        private global::System.String _AccountManagerName;
        partial void OnAccountManagerNameChanging(global::System.String value);
        partial void OnAccountManagerNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Currency
        {
            get
            {
                return _Currency;
            }
            set
            {
                OnCurrencyChanging(value);
                ReportPropertyChanging("Currency");
                _Currency = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Currency");
                OnCurrencyChanged();
            }
        }
        private global::System.String _Currency;
        partial void OnCurrencyChanging(global::System.String value);
        partial void OnCurrencyChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CakeModel", Name="CakeCampaign")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CakeCampaign : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new CakeCampaign object.
        /// </summary>
        /// <param name="campaign_Id">Initial value of the Campaign_Id property.</param>
        /// <param name="cakeOffer_Offer_Id">Initial value of the CakeOffer_Offer_Id property.</param>
        public static CakeCampaign CreateCakeCampaign(global::System.Int32 campaign_Id, global::System.Int32 cakeOffer_Offer_Id)
        {
            CakeCampaign cakeCampaign = new CakeCampaign();
            cakeCampaign.Campaign_Id = campaign_Id;
            cakeCampaign.CakeOffer_Offer_Id = cakeOffer_Offer_Id;
            return cakeCampaign;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Campaign_Id
        {
            get
            {
                return _Campaign_Id;
            }
            set
            {
                if (_Campaign_Id != value)
                {
                    OnCampaign_IdChanging(value);
                    ReportPropertyChanging("Campaign_Id");
                    _Campaign_Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Campaign_Id");
                    OnCampaign_IdChanged();
                }
            }
        }
        private global::System.Int32 _Campaign_Id;
        partial void OnCampaign_IdChanging(global::System.Int32 value);
        partial void OnCampaign_IdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CakeOffer_Offer_Id
        {
            get
            {
                return _CakeOffer_Offer_Id;
            }
            set
            {
                OnCakeOffer_Offer_IdChanging(value);
                ReportPropertyChanging("CakeOffer_Offer_Id");
                _CakeOffer_Offer_Id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CakeOffer_Offer_Id");
                OnCakeOffer_Offer_IdChanged();
            }
        }
        private global::System.Int32 _CakeOffer_Offer_Id;
        partial void OnCakeOffer_Offer_IdChanging(global::System.Int32 value);
        partial void OnCakeOffer_Offer_IdChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CakeModel", "FK_CakeOfferCakeCampaign", "CakeOffer")]
        public CakeOffer CakeOffer
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CakeOffer>("CakeModel.FK_CakeOfferCakeCampaign", "CakeOffer").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CakeOffer>("CakeModel.FK_CakeOfferCakeCampaign", "CakeOffer").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<CakeOffer> CakeOfferReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CakeOffer>("CakeModel.FK_CakeOfferCakeCampaign", "CakeOffer");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<CakeOffer>("CakeModel.FK_CakeOfferCakeCampaign", "CakeOffer", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CakeModel", "FK_CakeConversions_CakeCampaigns", "CakeConversion")]
        public EntityCollection<CakeConversion> CakeConversions
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<CakeConversion>("CakeModel.FK_CakeConversions_CakeCampaigns", "CakeConversion");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<CakeConversion>("CakeModel.FK_CakeConversions_CakeCampaigns", "CakeConversion", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CakeModel", Name="CakeContact")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CakeContact : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new CakeContact object.
        /// </summary>
        /// <param name="contact_Id">Initial value of the Contact_Id property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        public static CakeContact CreateCakeContact(global::System.Int32 contact_Id, global::System.String name)
        {
            CakeContact cakeContact = new CakeContact();
            cakeContact.Contact_Id = contact_Id;
            cakeContact.Name = name;
            return cakeContact;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Contact_Id
        {
            get
            {
                return _Contact_Id;
            }
            set
            {
                if (_Contact_Id != value)
                {
                    OnContact_IdChanging(value);
                    ReportPropertyChanging("Contact_Id");
                    _Contact_Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Contact_Id");
                    OnContact_IdChanged();
                }
            }
        }
        private global::System.Int32 _Contact_Id;
        partial void OnContact_IdChanging(global::System.Int32 value);
        partial void OnContact_IdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CakeModel", Name="CakeConversion")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CakeConversion : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new CakeConversion object.
        /// </summary>
        /// <param name="conversion_Id">Initial value of the Conversion_Id property.</param>
        /// <param name="campaign_Id">Initial value of the Campaign_Id property.</param>
        /// <param name="pricePaidCurrencyId">Initial value of the PricePaidCurrencyId property.</param>
        /// <param name="priceReceivedCurrencyId">Initial value of the PriceReceivedCurrencyId property.</param>
        public static CakeConversion CreateCakeConversion(global::System.Int32 conversion_Id, global::System.Int32 campaign_Id, global::System.Int32 pricePaidCurrencyId, global::System.Int32 priceReceivedCurrencyId)
        {
            CakeConversion cakeConversion = new CakeConversion();
            cakeConversion.Conversion_Id = conversion_Id;
            cakeConversion.Campaign_Id = campaign_Id;
            cakeConversion.PricePaidCurrencyId = pricePaidCurrencyId;
            cakeConversion.PriceReceivedCurrencyId = priceReceivedCurrencyId;
            return cakeConversion;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Conversion_Id
        {
            get
            {
                return _Conversion_Id;
            }
            set
            {
                if (_Conversion_Id != value)
                {
                    OnConversion_IdChanging(value);
                    ReportPropertyChanging("Conversion_Id");
                    _Conversion_Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Conversion_Id");
                    OnConversion_IdChanged();
                }
            }
        }
        private global::System.Int32 _Conversion_Id;
        partial void OnConversion_IdChanging(global::System.Int32 value);
        partial void OnConversion_IdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> ConversionDate
        {
            get
            {
                return _ConversionDate;
            }
            set
            {
                OnConversionDateChanging(value);
                ReportPropertyChanging("ConversionDate");
                _ConversionDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ConversionDate");
                OnConversionDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _ConversionDate;
        partial void OnConversionDateChanging(Nullable<global::System.DateTime> value);
        partial void OnConversionDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Affiliate_Id
        {
            get
            {
                return _Affiliate_Id;
            }
            set
            {
                OnAffiliate_IdChanging(value);
                ReportPropertyChanging("Affiliate_Id");
                _Affiliate_Id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Affiliate_Id");
                OnAffiliate_IdChanged();
            }
        }
        private Nullable<global::System.Int32> _Affiliate_Id;
        partial void OnAffiliate_IdChanging(Nullable<global::System.Int32> value);
        partial void OnAffiliate_IdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Offer_Id
        {
            get
            {
                return _Offer_Id;
            }
            set
            {
                OnOffer_IdChanging(value);
                ReportPropertyChanging("Offer_Id");
                _Offer_Id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Offer_Id");
                OnOffer_IdChanged();
            }
        }
        private Nullable<global::System.Int32> _Offer_Id;
        partial void OnOffer_IdChanging(Nullable<global::System.Int32> value);
        partial void OnOffer_IdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Advertiser_Id
        {
            get
            {
                return _Advertiser_Id;
            }
            set
            {
                OnAdvertiser_IdChanging(value);
                ReportPropertyChanging("Advertiser_Id");
                _Advertiser_Id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Advertiser_Id");
                OnAdvertiser_IdChanged();
            }
        }
        private Nullable<global::System.Int32> _Advertiser_Id;
        partial void OnAdvertiser_IdChanging(Nullable<global::System.Int32> value);
        partial void OnAdvertiser_IdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Campaign_Id
        {
            get
            {
                return _Campaign_Id;
            }
            set
            {
                OnCampaign_IdChanging(value);
                ReportPropertyChanging("Campaign_Id");
                _Campaign_Id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Campaign_Id");
                OnCampaign_IdChanged();
            }
        }
        private global::System.Int32 _Campaign_Id;
        partial void OnCampaign_IdChanging(global::System.Int32 value);
        partial void OnCampaign_IdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Creative_Id
        {
            get
            {
                return _Creative_Id;
            }
            set
            {
                OnCreative_IdChanging(value);
                ReportPropertyChanging("Creative_Id");
                _Creative_Id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Creative_Id");
                OnCreative_IdChanged();
            }
        }
        private Nullable<global::System.Int32> _Creative_Id;
        partial void OnCreative_IdChanging(Nullable<global::System.Int32> value);
        partial void OnCreative_IdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CreativeName
        {
            get
            {
                return _CreativeName;
            }
            set
            {
                OnCreativeNameChanging(value);
                ReportPropertyChanging("CreativeName");
                _CreativeName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CreativeName");
                OnCreativeNameChanged();
            }
        }
        private global::System.String _CreativeName;
        partial void OnCreativeNameChanging(global::System.String value);
        partial void OnCreativeNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Subid1
        {
            get
            {
                return _Subid1;
            }
            set
            {
                OnSubid1Changing(value);
                ReportPropertyChanging("Subid1");
                _Subid1 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Subid1");
                OnSubid1Changed();
            }
        }
        private global::System.String _Subid1;
        partial void OnSubid1Changing(global::System.String value);
        partial void OnSubid1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ConversionType
        {
            get
            {
                return _ConversionType;
            }
            set
            {
                OnConversionTypeChanging(value);
                ReportPropertyChanging("ConversionType");
                _ConversionType = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ConversionType");
                OnConversionTypeChanged();
            }
        }
        private global::System.String _ConversionType;
        partial void OnConversionTypeChanging(global::System.String value);
        partial void OnConversionTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PricePaid
        {
            get
            {
                return _PricePaid;
            }
            set
            {
                OnPricePaidChanging(value);
                ReportPropertyChanging("PricePaid");
                _PricePaid = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PricePaid");
                OnPricePaidChanged();
            }
        }
        private global::System.String _PricePaid;
        partial void OnPricePaidChanging(global::System.String value);
        partial void OnPricePaidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PriceReceived
        {
            get
            {
                return _PriceReceived;
            }
            set
            {
                OnPriceReceivedChanging(value);
                ReportPropertyChanging("PriceReceived");
                _PriceReceived = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PriceReceived");
                OnPriceReceivedChanged();
            }
        }
        private global::System.String _PriceReceived;
        partial void OnPriceReceivedChanging(global::System.String value);
        partial void OnPriceReceivedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String IpAddress
        {
            get
            {
                return _IpAddress;
            }
            set
            {
                OnIpAddressChanging(value);
                ReportPropertyChanging("IpAddress");
                _IpAddress = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("IpAddress");
                OnIpAddressChanged();
            }
        }
        private global::System.String _IpAddress;
        partial void OnIpAddressChanging(global::System.String value);
        partial void OnIpAddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> EomDatabase_Id
        {
            get
            {
                return _EomDatabase_Id;
            }
            set
            {
                OnEomDatabase_IdChanging(value);
                ReportPropertyChanging("EomDatabase_Id");
                _EomDatabase_Id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EomDatabase_Id");
                OnEomDatabase_IdChanged();
            }
        }
        private Nullable<global::System.Int32> _EomDatabase_Id;
        partial void OnEomDatabase_IdChanging(Nullable<global::System.Int32> value);
        partial void OnEomDatabase_IdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> EomItem_Id
        {
            get
            {
                return _EomItem_Id;
            }
            set
            {
                OnEomItem_IdChanging(value);
                ReportPropertyChanging("EomItem_Id");
                _EomItem_Id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EomItem_Id");
                OnEomItem_IdChanged();
            }
        }
        private Nullable<global::System.Int32> _EomItem_Id;
        partial void OnEomItem_IdChanging(Nullable<global::System.Int32> value);
        partial void OnEomItem_IdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String EomItemName
        {
            get
            {
                return _EomItemName;
            }
            set
            {
                OnEomItemNameChanging(value);
                ReportPropertyChanging("EomItemName");
                _EomItemName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("EomItemName");
                OnEomItemNameChanged();
            }
        }
        private global::System.String _EomItemName;
        partial void OnEomItemNameChanging(global::System.String value);
        partial void OnEomItemNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PricePaidCurrencyId
        {
            get
            {
                return _PricePaidCurrencyId;
            }
            set
            {
                OnPricePaidCurrencyIdChanging(value);
                ReportPropertyChanging("PricePaidCurrencyId");
                _PricePaidCurrencyId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PricePaidCurrencyId");
                OnPricePaidCurrencyIdChanged();
            }
        }
        private global::System.Int32 _PricePaidCurrencyId;
        partial void OnPricePaidCurrencyIdChanging(global::System.Int32 value);
        partial void OnPricePaidCurrencyIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PriceReceivedCurrencyId
        {
            get
            {
                return _PriceReceivedCurrencyId;
            }
            set
            {
                OnPriceReceivedCurrencyIdChanging(value);
                ReportPropertyChanging("PriceReceivedCurrencyId");
                _PriceReceivedCurrencyId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PriceReceivedCurrencyId");
                OnPriceReceivedCurrencyIdChanged();
            }
        }
        private global::System.Int32 _PriceReceivedCurrencyId;
        partial void OnPriceReceivedCurrencyIdChanging(global::System.Int32 value);
        partial void OnPriceReceivedCurrencyIdChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CakeModel", "FK_CakeConversions_CakeCampaigns", "CakeCampaign")]
        public CakeCampaign CakeCampaign
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CakeCampaign>("CakeModel.FK_CakeConversions_CakeCampaigns", "CakeCampaign").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CakeCampaign>("CakeModel.FK_CakeConversions_CakeCampaigns", "CakeCampaign").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<CakeCampaign> CakeCampaignReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CakeCampaign>("CakeModel.FK_CakeConversions_CakeCampaigns", "CakeCampaign");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<CakeCampaign>("CakeModel.FK_CakeConversions_CakeCampaigns", "CakeCampaign", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CakeModel", Name="CakeOffer")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CakeOffer : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new CakeOffer object.
        /// </summary>
        /// <param name="offer_Id">Initial value of the Offer_Id property.</param>
        public static CakeOffer CreateCakeOffer(global::System.Int32 offer_Id)
        {
            CakeOffer cakeOffer = new CakeOffer();
            cakeOffer.Offer_Id = offer_Id;
            return cakeOffer;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Offer_Id
        {
            get
            {
                return _Offer_Id;
            }
            set
            {
                if (_Offer_Id != value)
                {
                    OnOffer_IdChanging(value);
                    ReportPropertyChanging("Offer_Id");
                    _Offer_Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Offer_Id");
                    OnOffer_IdChanged();
                }
            }
        }
        private global::System.Int32 _Offer_Id;
        partial void OnOffer_IdChanging(global::System.Int32 value);
        partial void OnOffer_IdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String OfferName
        {
            get
            {
                return _OfferName;
            }
            set
            {
                OnOfferNameChanging(value);
                ReportPropertyChanging("OfferName");
                _OfferName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("OfferName");
                OnOfferNameChanged();
            }
        }
        private global::System.String _OfferName;
        partial void OnOfferNameChanging(global::System.String value);
        partial void OnOfferNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Advertiser_Id
        {
            get
            {
                return _Advertiser_Id;
            }
            set
            {
                OnAdvertiser_IdChanging(value);
                ReportPropertyChanging("Advertiser_Id");
                _Advertiser_Id = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Advertiser_Id");
                OnAdvertiser_IdChanged();
            }
        }
        private global::System.String _Advertiser_Id;
        partial void OnAdvertiser_IdChanging(global::System.String value);
        partial void OnAdvertiser_IdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String VerticalName
        {
            get
            {
                return _VerticalName;
            }
            set
            {
                OnVerticalNameChanging(value);
                ReportPropertyChanging("VerticalName");
                _VerticalName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("VerticalName");
                OnVerticalNameChanged();
            }
        }
        private global::System.String _VerticalName;
        partial void OnVerticalNameChanging(global::System.String value);
        partial void OnVerticalNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String OfferType
        {
            get
            {
                return _OfferType;
            }
            set
            {
                OnOfferTypeChanging(value);
                ReportPropertyChanging("OfferType");
                _OfferType = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("OfferType");
                OnOfferTypeChanged();
            }
        }
        private global::System.String _OfferType;
        partial void OnOfferTypeChanging(global::System.String value);
        partial void OnOfferTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String StatusName
        {
            get
            {
                return _StatusName;
            }
            set
            {
                OnStatusNameChanging(value);
                ReportPropertyChanging("StatusName");
                _StatusName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("StatusName");
                OnStatusNameChanged();
            }
        }
        private global::System.String _StatusName;
        partial void OnStatusNameChanging(global::System.String value);
        partial void OnStatusNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DefaultPriceFormat
        {
            get
            {
                return _DefaultPriceFormat;
            }
            set
            {
                OnDefaultPriceFormatChanging(value);
                ReportPropertyChanging("DefaultPriceFormat");
                _DefaultPriceFormat = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DefaultPriceFormat");
                OnDefaultPriceFormatChanged();
            }
        }
        private global::System.String _DefaultPriceFormat;
        partial void OnDefaultPriceFormatChanging(global::System.String value);
        partial void OnDefaultPriceFormatChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DefaultPayout
        {
            get
            {
                return _DefaultPayout;
            }
            set
            {
                OnDefaultPayoutChanging(value);
                ReportPropertyChanging("DefaultPayout");
                _DefaultPayout = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DefaultPayout");
                OnDefaultPayoutChanged();
            }
        }
        private global::System.String _DefaultPayout;
        partial void OnDefaultPayoutChanging(global::System.String value);
        partial void OnDefaultPayoutChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PriceReceived
        {
            get
            {
                return _PriceReceived;
            }
            set
            {
                OnPriceReceivedChanging(value);
                ReportPropertyChanging("PriceReceived");
                _PriceReceived = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PriceReceived");
                OnPriceReceivedChanged();
            }
        }
        private global::System.String _PriceReceived;
        partial void OnPriceReceivedChanging(global::System.String value);
        partial void OnPriceReceivedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Secure
        {
            get
            {
                return _Secure;
            }
            set
            {
                OnSecureChanging(value);
                ReportPropertyChanging("Secure");
                _Secure = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Secure");
                OnSecureChanged();
            }
        }
        private global::System.String _Secure;
        partial void OnSecureChanging(global::System.String value);
        partial void OnSecureChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String OfferLink
        {
            get
            {
                return _OfferLink;
            }
            set
            {
                OnOfferLinkChanging(value);
                ReportPropertyChanging("OfferLink");
                _OfferLink = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("OfferLink");
                OnOfferLinkChanged();
            }
        }
        private global::System.String _OfferLink;
        partial void OnOfferLinkChanging(global::System.String value);
        partial void OnOfferLinkChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ThumbnailImageUrl
        {
            get
            {
                return _ThumbnailImageUrl;
            }
            set
            {
                OnThumbnailImageUrlChanging(value);
                ReportPropertyChanging("ThumbnailImageUrl");
                _ThumbnailImageUrl = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ThumbnailImageUrl");
                OnThumbnailImageUrlChanged();
            }
        }
        private global::System.String _ThumbnailImageUrl;
        partial void OnThumbnailImageUrlChanging(global::System.String value);
        partial void OnThumbnailImageUrlChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ExpirationDate
        {
            get
            {
                return _ExpirationDate;
            }
            set
            {
                OnExpirationDateChanging(value);
                ReportPropertyChanging("ExpirationDate");
                _ExpirationDate = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ExpirationDate");
                OnExpirationDateChanged();
            }
        }
        private global::System.String _ExpirationDate;
        partial void OnExpirationDateChanging(global::System.String value);
        partial void OnExpirationDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CookieDays
        {
            get
            {
                return _CookieDays;
            }
            set
            {
                OnCookieDaysChanging(value);
                ReportPropertyChanging("CookieDays");
                _CookieDays = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CookieDays");
                OnCookieDaysChanged();
            }
        }
        private global::System.String _CookieDays;
        partial void OnCookieDaysChanging(global::System.String value);
        partial void OnCookieDaysChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CookieDaysImpressions
        {
            get
            {
                return _CookieDaysImpressions;
            }
            set
            {
                OnCookieDaysImpressionsChanging(value);
                ReportPropertyChanging("CookieDaysImpressions");
                _CookieDaysImpressions = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CookieDaysImpressions");
                OnCookieDaysImpressionsChanged();
            }
        }
        private global::System.String _CookieDaysImpressions;
        partial void OnCookieDaysImpressionsChanging(global::System.String value);
        partial void OnCookieDaysImpressionsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DateCreated
        {
            get
            {
                return _DateCreated;
            }
            set
            {
                OnDateCreatedChanging(value);
                ReportPropertyChanging("DateCreated");
                _DateCreated = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DateCreated");
                OnDateCreatedChanged();
            }
        }
        private global::System.String _DateCreated;
        partial void OnDateCreatedChanging(global::System.String value);
        partial void OnDateCreatedChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CakeModel", "FK_CakeOfferCakeCampaign", "CakeCampaign")]
        public EntityCollection<CakeCampaign> CakeCampaigns
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<CakeCampaign>("CakeModel.FK_CakeOfferCakeCampaign", "CakeCampaign");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<CakeCampaign>("CakeModel.FK_CakeOfferCakeCampaign", "CakeCampaign", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CakeModel", Name="CakeUtilityError")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CakeUtilityError : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new CakeUtilityError object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static CakeUtilityError CreateCakeUtilityError(global::System.Int32 id)
        {
            CakeUtilityError cakeUtilityError = new CakeUtilityError();
            cakeUtilityError.Id = id;
            return cakeUtilityError;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Tag
        {
            get
            {
                return _Tag;
            }
            set
            {
                OnTagChanging(value);
                ReportPropertyChanging("Tag");
                _Tag = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Tag");
                OnTagChanged();
            }
        }
        private global::System.String _Tag;
        partial void OnTagChanging(global::System.String value);
        partial void OnTagChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ExceptionMessage
        {
            get
            {
                return _ExceptionMessage;
            }
            set
            {
                OnExceptionMessageChanging(value);
                ReportPropertyChanging("ExceptionMessage");
                _ExceptionMessage = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ExceptionMessage");
                OnExceptionMessageChanged();
            }
        }
        private global::System.String _ExceptionMessage;
        partial void OnExceptionMessageChanging(global::System.String value);
        partial void OnExceptionMessageChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ExceptionStackTrace
        {
            get
            {
                return _ExceptionStackTrace;
            }
            set
            {
                OnExceptionStackTraceChanging(value);
                ReportPropertyChanging("ExceptionStackTrace");
                _ExceptionStackTrace = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ExceptionStackTrace");
                OnExceptionStackTraceChanged();
            }
        }
        private global::System.String _ExceptionStackTrace;
        partial void OnExceptionStackTraceChanging(global::System.String value);
        partial void OnExceptionStackTraceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String InnerExceptionMessage
        {
            get
            {
                return _InnerExceptionMessage;
            }
            set
            {
                OnInnerExceptionMessageChanging(value);
                ReportPropertyChanging("InnerExceptionMessage");
                _InnerExceptionMessage = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("InnerExceptionMessage");
                OnInnerExceptionMessageChanged();
            }
        }
        private global::System.String _InnerExceptionMessage;
        partial void OnInnerExceptionMessageChanging(global::System.String value);
        partial void OnInnerExceptionMessageChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String InnerExceptionStackTrace
        {
            get
            {
                return _InnerExceptionStackTrace;
            }
            set
            {
                OnInnerExceptionStackTraceChanging(value);
                ReportPropertyChanging("InnerExceptionStackTrace");
                _InnerExceptionStackTrace = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("InnerExceptionStackTrace");
                OnInnerExceptionStackTraceChanged();
            }
        }
        private global::System.String _InnerExceptionStackTrace;
        partial void OnInnerExceptionStackTraceChanging(global::System.String value);
        partial void OnInnerExceptionStackTraceChanged();

        #endregion
    
    }

    #endregion
    
}
