//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EomTool.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Affiliate
    {
        public int id { get; set; }
        public string name { get; set; }
        public int media_buyer_id { get; set; }
        public int affid { get; set; }
        public int currency_id { get; set; }
        public string email { get; set; }
        public string add_code { get; set; }
        public Nullable<int> net_term_type_id { get; set; }
        public int payment_method_id { get; set; }
        public string name2 { get; set; }
        public Nullable<System.DateTime> date_created { get; set; }
        public Nullable<System.DateTime> date_modified { get; set; }
        public Nullable<int> tracking_system_id { get; set; }
        public Nullable<int> external_id { get; set; }
        public string status { get; set; }
        public bool margin_exempt { get; set; }
        public string payment_on_hold { get; set; }
        public string qb_name { get; set; }
    
        public virtual Currency Currency { get; set; }
        public virtual MediaBuyer MediaBuyer { get; set; }
        public virtual NetTermType NetTermType { get; set; }
        public virtual TrackingSystem TrackingSystem { get; set; }
        public virtual AffiliatePaymentMethod AffiliatePaymentMethod { get; set; }
    }
}
