//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EomTool.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnalystRole
    {
        public int person_id { get; set; }
        public int pid { get; set; }
        public int affid { get; set; }
    
        public virtual Person Person { get; set; }
    }
}
