//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EomTool.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class BatchUpdate
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BatchUpdate()
        {
            this.Batches = new HashSet<Batch>();
        }
    
        public int id { get; set; }
        public string note { get; set; }
        public string author { get; set; }
        public System.DateTime date_created { get; set; }
        public Nullable<int> media_buyer_approval_status_id { get; set; }
        public string extra { get; set; }
        public Nullable<int> from_media_buyer_approval_status_id { get; set; }
    
        public virtual MediaBuyerApprovalStatus MediaBuyerApprovalStatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Batch> Batches { get; set; }
        public virtual MediaBuyerApprovalStatus MediaBuyerApprovalStatusFrom { get; set; }
    }
}
