//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EomTool.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DADatabase
    {
        public int id { get; set; }
        public string name { get; set; }
        public string connection_string { get; set; }
        public Nullable<System.DateTime> effective_date { get; set; }
        public string am_view_name { get; set; }
        public bool initialized { get; set; }
    }
}
