//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EomTool.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceItem
    {
        public int id { get; set; }
        public int invoice_id { get; set; }
        public Nullable<int> pid { get; set; }
        public Nullable<int> affid { get; set; }
        public int currency_id { get; set; }
        public decimal amount_per_unit { get; set; }
        public int num_units { get; set; }
        public Nullable<decimal> total_amount { get; set; }
        public Nullable<int> unit_type_id { get; set; }
    
        public virtual Currency Currency { get; set; }
        public virtual Invoice Invoice { get; set; }
        public virtual UnitType UnitType { get; set; }
    }
}
