//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EomTool.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MarginApproval
    {
        public int id { get; set; }
        public Nullable<int> pid { get; set; }
        public Nullable<int> affid { get; set; }
        public Nullable<int> revenue_currency_id { get; set; }
        public Nullable<decimal> total_revenue { get; set; }
        public Nullable<int> cost_currency_id { get; set; }
        public Nullable<decimal> total_cost { get; set; }
        public Nullable<decimal> margin_pct { get; set; }
        public string comment { get; set; }
        public string added_by { get; set; }
        public System.DateTime created { get; set; }
        public Nullable<System.DateTime> used { get; set; }
    
        public virtual Currency RevenueCurrency { get; set; }
        public virtual Currency CostCurrency { get; set; }
    }
}
