//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EomTool.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentBatch
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PaymentBatch()
        {
            this.Items = new HashSet<Item>();
            this.PaymentBatchChildren = new HashSet<PaymentBatch>();
        }
    
        public int id { get; set; }
        public string approver_identity { get; set; }
        public int payment_batch_state_id { get; set; }
        public bool is_current { get; set; }
        public Nullable<decimal> payment_threshold { get; set; }
        public Nullable<int> parent_batch_id { get; set; }
        public Nullable<int> payment_method_id { get; set; }
        public string name { get; set; }
        public Nullable<System.DateTime> date_sent { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Item> Items { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaymentBatch> PaymentBatchChildren { get; set; }
        public virtual PaymentBatch PaymentBatchParent { get; set; }
        public virtual PaymentBatchState PaymentBatchState { get; set; }
        public virtual AffiliatePaymentMethod AffiliatePaymentMethod { get; set; }
    }
}
