//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EomTool.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PublisherReportDetail
    {
        public string PublisherName { get; set; }
        public string NetTermTypeName { get; set; }
        public string AffiliateCurrencyName { get; set; }
        public Nullable<decimal> SumItemTotalCost { get; set; }
        public string ItemAccountingStatusName { get; set; }
        public string CampaignStatusName { get; set; }
        public string CampaignName { get; set; }
        public Nullable<decimal> NumUnits { get; set; }
        public Nullable<decimal> CostPerUnit { get; set; }
        public string AffiliateAddCode { get; set; }
        public string IsCPM { get; set; }
        public string MediaBuyer { get; set; }
        public string ItemIDs { get; set; }
    }
}
