//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EomTool.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PublisherReportSummary
    {
        public string Name { get; set; }
        public string Net_Terms { get; set; }
        public string Curr { get; set; }
        public Nullable<decimal> To_Be_Paid { get; set; }
        public Nullable<decimal> Paid { get; set; }
        public Nullable<decimal> Total { get; set; }
    }
}
