// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 12.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CakeExtracter.Reports
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "G:\GitHub\da-projects\3\CakeExtracter\CakeExtracter\Reports\SearchReportRuntimeTextTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "12.0.0.0")]
    public partial class SearchReportRuntimeTextTemplate : SearchReportRuntimeTextTemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write(@"<table width=""620"" border=""0"" align=""center"" cellpadding=""0"" cellspacing=""0"" style=""border:1px solid #c7c3c7;"">
<tr><td style=""font-size:0px;"">
<table width=""620"" border=""0"" cellspacing=""0"" cellpadding=""0"">
  <tr>
    <td width=""13"" rowspan=""2"" align=""left"" valign=""top"">&nbsp;</td>
    <td width=""195"" rowspan=""2"" align=""left"" valign=""top""><img src=""https://portal.directagents.com/Images/logo1.png"" alt="""" width=""152"" height=""86"" /></td>
    <td height=""24"" colspan=""2"" align=""left"" valign=""top"">&nbsp;</td>
  </tr>
  <tr>
    <td width=""399"" align=""right"" valign=""top""><strong style=""font-family: Arial, Helvetica, sans-serif; text-align: center; font-size: 18px;"">Weekly Summary Report for ");
            
            #line 15 "G:\GitHub\da-projects\3\CakeExtracter\CakeExtracter\Reports\SearchReportRuntimeTextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.SearchProfile.SearchProfileName));
            
            #line default
            #line hidden
            this.Write(@"</strong></td>
    <td width=""13"" align=""right"" valign=""top"">&nbsp;</td>
  </tr>
  <tr>
    <td align=""left"" valign=""top"">&nbsp;</td>
    <td colspan=""2"" align=""left"" valign=""top"" style=""font-family: Arial, Helvetica, sans-serif; font-size: 14px;"">Thank you for using the Direct Agents client portal. A summary of your campaign performance is included below. Please <a href=""http://portal.directagents.com/"" style=""color:#37A5F2;""><strong>log in</strong></a> to access your complete reports.<br><br></td>
    <td align=""right"" valign=""top"">&nbsp;</td>
  </tr>
  <tr>
    <td colspan=""4"" height=""80"" align=""center"" valign=""middle"">
   
    <table width=""620""  align=""center"" cellpadding=""0"" cellspacing=""0"" style=""border-top:1px solid #c7c3c7; border-bottom:1px solid #c7c3c7; border-left:0px solid #c7c3c7; border-right:0px solid #c7c3c7;"">
      <tr>
        <td height=""30"" align=""left"" valign=""middle"" bgcolor=""#e5e5e5"" style=""color: #000; border-right:1px solid #c7c3c7; font-family: Arial, Helvetica, sans-serif; font-size: 13px;"">&nbsp;&nbsp;Week</td>
      ");
            
            #line 29 "G:\GitHub\da-projects\3\CakeExtracter\CakeExtracter\Reports\SearchReportRuntimeTextTemplate.tt"
 if (this.SearchProfile.ShowRevenue) { 
            
            #line default
            #line hidden
            this.Write(@"        <td height=""30"" align=""left"" valign=""middle"" bgcolor=""#e5e5e5"" style=""color: #000; border-right:1px solid #c7c3c7; font-family: Arial, Helvetica, sans-serif; font-size: 13px;"">&nbsp;&nbsp;Revenue</td>
        <td height=""30"" align=""left"" valign=""middle"" bgcolor=""#e5e5e5"" style=""color: #000; border-right:1px solid #c7c3c7; font-family: Arial, Helvetica, sans-serif; font-size: 13px;"">&nbsp;&nbsp;Cost</td>
        <td height=""30"" align=""left"" valign=""middle"" bgcolor=""#e5e5e5"" style=""color: #000; border-right:1px solid #c7c3c7; font-family: Arial, Helvetica, sans-serif; font-size: 13px;"">&nbsp;&nbsp;ROAS</td>
        <td height=""30"" align=""left"" valign=""middle"" bgcolor=""#e5e5e5"" style=""color: #000; border-right:1px solid #c7c3c7; font-family: Arial, Helvetica, sans-serif; font-size: 13px;"">&nbsp;&nbsp;Margin</td>
        <td height=""30"" align=""left"" valign=""middle"" bgcolor=""#e5e5e5"" style=""color: #000; border-right:1px solid #c7c3c7; font-family: Arial, Helvetica, sans-serif; font-size: 13px;"">&nbsp;&nbsp;Orders</td>
        <td height=""30"" align=""left"" valign=""middle"" bgcolor=""#e5e5e5"" style=""color: #000; border-right:1px solid #c7c3c7; font-family: Arial, Helvetica, sans-serif; font-size: 13px;"">&nbsp;&nbsp;CPO</td>
      ");
            
            #line 36 "G:\GitHub\da-projects\3\CakeExtracter\CakeExtracter\Reports\SearchReportRuntimeTextTemplate.tt"
 } else { 
            
            #line default
            #line hidden
            this.Write(@"        <td height=""30"" align=""left"" valign=""middle"" bgcolor=""#e5e5e5"" style=""color: #000; border-right:1px solid #c7c3c7; font-family: Arial, Helvetica, sans-serif; font-size: 13px;"">&nbsp;&nbsp;Clicks</td>
        <td height=""30"" align=""left"" valign=""middle"" bgcolor=""#e5e5e5"" style=""color: #000; border-right:1px solid #c7c3c7; font-family: Arial, Helvetica, sans-serif; font-size: 13px;"">&nbsp;&nbsp;Impressions</td>
        <td height=""30"" align=""left"" valign=""middle"" bgcolor=""#e5e5e5"" style=""color: #000; border-right:1px solid #c7c3c7; font-family: Arial, Helvetica, sans-serif; font-size: 13px;"">&nbsp;&nbsp;CTR</td>
        <td height=""30"" align=""left"" valign=""middle"" bgcolor=""#e5e5e5"" style=""color: #000; border-right:1px solid #c7c3c7; font-family: Arial, Helvetica, sans-serif; font-size: 13px;"">&nbsp;&nbsp;Spend</td>
        <td height=""30"" align=""left"" valign=""middle"" bgcolor=""#e5e5e5"" style=""color: #000; border-right:1px solid #c7c3c7; font-family: Arial, Helvetica, sans-serif; font-size: 13px;"">&nbsp;&nbsp;Leads</td>
      ");
            
            #line 42 "G:\GitHub\da-projects\3\CakeExtracter\CakeExtracter\Reports\SearchReportRuntimeTextTemplate.tt"
 if (this.SearchProfile.ShowCalls) { 
            
            #line default
            #line hidden
            this.Write(@"        <td height=""30"" align=""left"" valign=""middle"" bgcolor=""#e5e5e5"" style=""color: #000; border-right:1px solid #c7c3c7; font-family: Arial, Helvetica, sans-serif; font-size: 13px;"">&nbsp;&nbsp;Calls</td>
        <td height=""30"" align=""left"" valign=""middle"" bgcolor=""#e5e5e5"" style=""color: #000; border-right:1px solid #c7c3c7; font-family: Arial, Helvetica, sans-serif; font-size: 13px;"">&nbsp;&nbsp;Total Leads</td>
      ");
            
            #line 45 "G:\GitHub\da-projects\3\CakeExtracter\CakeExtracter\Reports\SearchReportRuntimeTextTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("        <td height=\"30\" align=\"left\" valign=\"middle\" bgcolor=\"#e5e5e5\" style=\"col" +
                    "or: #000; border-right:1px solid #c7c3c7; font-family: Arial, Helvetica, sans-se" +
                    "rif; font-size: 13px;\">&nbsp;&nbsp;CPL</td>\r\n      ");
            
            #line 47 "G:\GitHub\da-projects\3\CakeExtracter\CakeExtracter\Reports\SearchReportRuntimeTextTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("      </tr>\r\n\r\n      <tr>\r\n        <td height=\"30\" align=\"left\" valign=\"middle\" b" +
                    "gcolor=\"#FFFFFF\" style=\"color: #000; border-right:1px solid #c7c3c7; font-family" +
                    ": Arial, Helvetica, sans-serif; font-size: 13px; text-align: center; font-weight" +
                    ": bold;\">");
            
            #line 51 "G:\GitHub\da-projects\3\CakeExtracter\CakeExtracter\Reports\SearchReportRuntimeTextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Line1stat.Title));
            
            #line default
            #line hidden
            this.Write("</td>\r\n      ");
            
            #line 52 "G:\GitHub\da-projects\3\CakeExtracter\CakeExtracter\Reports\SearchReportRuntimeTextTemplate.tt"
 if (this.SearchProfile.ShowRevenue) { 
            
            #line default
            #line hidden
            this.Write("        <td height=\"30\" align=\"left\" valign=\"middle\" bgcolor=\"#FFFFFF\" style=\"col" +
                    "or: #000; border-right:1px solid #c7c3c7; font-family: Arial, Helvetica, sans-se" +
                    "rif; font-size: 13px; text-align: center; font-weight: bold;\">");
            
            #line 53 "G:\GitHub\da-projects\3\CakeExtracter\CakeExtracter\Reports\SearchReportRuntimeTextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Currency(Line1stat.Revenue)));
            
            #line default
            #line hidden
            this.Write("</td>\r\n        <td height=\"30\" align=\"left\" valign=\"middle\" bgcolor=\"#FFFFFF\" sty" +
                    "le=\"color: #000; border-right:1px solid #c7c3c7; font-family: Arial, Helvetica, " +
                    "sans-serif; font-size: 13px; text-align: center; font-weight: bold;\">");
            
            #line 54 "G:\GitHub\da-projects\3\CakeExtracter\CakeExtracter\Reports\SearchReportRuntimeTextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Currency(Line1stat.Cost)));
            
            #line default
            #line hidden
            this.Write("</td>\r\n        <td height=\"30\" align=\"left\" valign=\"middle\" bgcolor=\"#FFFFFF\" sty" +
                    "le=\"color: #000; border-right:1px solid #c7c3c7; font-family: Arial, Helvetica, " +
                    "sans-serif; font-size: 13px; text-align: center; font-weight: bold;\">");
            
            #line 55 "G:\GitHub\da-projects\3\CakeExtracter\CakeExtracter\Reports\SearchReportRuntimeTextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Integer(Line1stat.ROAS)));
            
            #line default
            #line hidden
            this.Write("%</td>\r\n        <td height=\"30\" align=\"left\" valign=\"middle\" bgcolor=\"#FFFFFF\" st" +
                    "yle=\"color: #000; border-right:1px solid #c7c3c7; font-family: Arial, Helvetica," +
                    " sans-serif; font-size: 13px; text-align: center; font-weight: bold;\">");
            
            #line 56 "G:\GitHub\da-projects\3\CakeExtracter\CakeExtracter\Reports\SearchReportRuntimeTextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Currency(Line1stat.Margin)));
            
            #line default
            #line hidden
            this.Write("</td>\r\n        <td height=\"30\" align=\"left\" valign=\"middle\" bgcolor=\"#FFFFFF\" sty" +
                    "le=\"color: #000; border-right:1px solid #c7c3c7; font-family: Arial, Helvetica, " +
                    "sans-serif; font-size: 13px; text-align: center; font-weight: bold;\">");
            
            #line 57 "G:\GitHub\da-projects\3\CakeExtracter\CakeExtracter\Reports\SearchReportRuntimeTextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Integer(Line1stat.Orders)));
            
            #line default
            #line hidden
            this.Write("</td>\r\n        <td height=\"30\" align=\"left\" valign=\"middle\" bgcolor=\"#FFFFFF\" sty" +
                    "le=\"color: #000; border-right:1px solid #c7c3c7; font-family: Arial, Helvetica, " +
                    "sans-serif; font-size: 13px; text-align: center; font-weight: bold;\">");
            
            #line 58 "G:\GitHub\da-projects\3\CakeExtracter\CakeExtracter\Reports\SearchReportRuntimeTextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Currency(Line1stat.CPO)));
            
            #line default
            #line hidden
            this.Write("</td>\r\n      ");
            
            #line 59 "G:\GitHub\da-projects\3\CakeExtracter\CakeExtracter\Reports\SearchReportRuntimeTextTemplate.tt"
 } else { 
            
            #line default
            #line hidden
            this.Write("        <td height=\"30\" align=\"left\" valign=\"middle\" bgcolor=\"#FFFFFF\" style=\"col" +
                    "or: #000; border-right:1px solid #c7c3c7; font-family: Arial, Helvetica, sans-se" +
                    "rif; font-size: 13px; text-align: center; font-weight: bold;\">");
            
            #line 60 "G:\GitHub\da-projects\3\CakeExtracter\CakeExtracter\Reports\SearchReportRuntimeTextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Integer(Line1stat.Clicks)));
            
            #line default
            #line hidden
            this.Write("</td>\r\n        <td height=\"30\" align=\"left\" valign=\"middle\" bgcolor=\"#FFFFFF\" sty" +
                    "le=\"color: #000; border-right:1px solid #c7c3c7; font-family: Arial, Helvetica, " +
                    "sans-serif; font-size: 13px; text-align: center; font-weight: bold;\">");
            
            #line 61 "G:\GitHub\da-projects\3\CakeExtracter\CakeExtracter\Reports\SearchReportRuntimeTextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Integer(Line1stat.Impressions)));
            
            #line default
            #line hidden
            this.Write("</td>\r\n        <td height=\"30\" align=\"left\" valign=\"middle\" bgcolor=\"#FFFFFF\" sty" +
                    "le=\"color: #000; border-right:1px solid #c7c3c7; font-family: Arial, Helvetica, " +
                    "sans-serif; font-size: 13px; text-align: center; font-weight: bold;\">");
            
            #line 62 "G:\GitHub\da-projects\3\CakeExtracter\CakeExtracter\Reports\SearchReportRuntimeTextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Decimal(Line1stat.CTR)));
            
            #line default
            #line hidden
            this.Write("%</td>\r\n        <td height=\"30\" align=\"left\" valign=\"middle\" bgcolor=\"#FFFFFF\" st" +
                    "yle=\"color: #000; border-right:1px solid #c7c3c7; font-family: Arial, Helvetica," +
                    " sans-serif; font-size: 13px; text-align: center; font-weight: bold;\">");
            
            #line 63 "G:\GitHub\da-projects\3\CakeExtracter\CakeExtracter\Reports\SearchReportRuntimeTextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Currency(Line1stat.Cost)));
            
            #line default
            #line hidden
            this.Write("</td>\r\n        <td height=\"30\" align=\"left\" valign=\"middle\" bgcolor=\"#FFFFFF\" sty" +
                    "le=\"color: #000; border-right:1px solid #c7c3c7; font-family: Arial, Helvetica, " +
                    "sans-serif; font-size: 13px; text-align: center; font-weight: bold;\">");
            
            #line 64 "G:\GitHub\da-projects\3\CakeExtracter\CakeExtracter\Reports\SearchReportRuntimeTextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Integer(Line1stat.Orders)));
            
            #line default
            #line hidden
            this.Write("</td>\r\n      ");
            
            #line 65 "G:\GitHub\da-projects\3\CakeExtracter\CakeExtracter\Reports\SearchReportRuntimeTextTemplate.tt"
 if (this.SearchProfile.ShowCalls) { 
            
            #line default
            #line hidden
            this.Write("        <td height=\"30\" align=\"left\" valign=\"middle\" bgcolor=\"#FFFFFF\" style=\"col" +
                    "or: #000; border-right:1px solid #c7c3c7; font-family: Arial, Helvetica, sans-se" +
                    "rif; font-size: 13px; text-align: center; font-weight: bold;\">");
            
            #line 66 "G:\GitHub\da-projects\3\CakeExtracter\CakeExtracter\Reports\SearchReportRuntimeTextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Integer(Line1stat.Calls)));
            
            #line default
            #line hidden
            this.Write("</td>\r\n        <td height=\"30\" align=\"left\" valign=\"middle\" bgcolor=\"#FFFFFF\" sty" +
                    "le=\"color: #000; border-right:1px solid #c7c3c7; font-family: Arial, Helvetica, " +
                    "sans-serif; font-size: 13px; text-align: center; font-weight: bold;\">");
            
            #line 67 "G:\GitHub\da-projects\3\CakeExtracter\CakeExtracter\Reports\SearchReportRuntimeTextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Integer(Line1stat.TotalLeads)));
            
            #line default
            #line hidden
            this.Write("</td>\r\n      ");
            
            #line 68 "G:\GitHub\da-projects\3\CakeExtracter\CakeExtracter\Reports\SearchReportRuntimeTextTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("        <td height=\"30\" align=\"left\" valign=\"middle\" bgcolor=\"#FFFFFF\" style=\"col" +
                    "or: #000; border-right:1px solid #c7c3c7; font-family: Arial, Helvetica, sans-se" +
                    "rif; font-size: 13px; text-align: center; font-weight: bold;\">");
            
            #line 69 "G:\GitHub\da-projects\3\CakeExtracter\CakeExtracter\Reports\SearchReportRuntimeTextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Currency(Line1stat.CPL)));
            
            #line default
            #line hidden
            this.Write("</td>\r\n      ");
            
            #line 70 "G:\GitHub\da-projects\3\CakeExtracter\CakeExtracter\Reports\SearchReportRuntimeTextTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("      </tr>\r\n\r\n");
            
            #line 73 "G:\GitHub\da-projects\3\CakeExtracter\CakeExtracter\Reports\SearchReportRuntimeTextTemplate.tt"
 if (this.Line2stat != null) { 
            
            #line default
            #line hidden
            this.Write("      <tr>\r\n        <td height=\"30\" align=\"left\" valign=\"middle\" bgcolor=\"#FFFFFF" +
                    "\" style=\"color: #000; border-right:1px solid #c7c3c7; font-family: Arial, Helvet" +
                    "ica, sans-serif; font-size: 13px; text-align: center; font-weight: bold;\">");
            
            #line 75 "G:\GitHub\da-projects\3\CakeExtracter\CakeExtracter\Reports\SearchReportRuntimeTextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Line2stat.Title));
            
            #line default
            #line hidden
            this.Write("</td>\r\n      ");
            
            #line 76 "G:\GitHub\da-projects\3\CakeExtracter\CakeExtracter\Reports\SearchReportRuntimeTextTemplate.tt"
 if (this.SearchProfile.ShowRevenue) { 
            
            #line default
            #line hidden
            this.Write("        <td height=\"30\" align=\"left\" valign=\"middle\" bgcolor=\"#FFFFFF\" style=\"col" +
                    "or: #000; border-right:1px solid #c7c3c7; font-family: Arial, Helvetica, sans-se" +
                    "rif; font-size: 13px; text-align: center; font-weight: bold;\">");
            
            #line 77 "G:\GitHub\da-projects\3\CakeExtracter\CakeExtracter\Reports\SearchReportRuntimeTextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Currency(Line2stat.Revenue)));
            
            #line default
            #line hidden
            this.Write("</td>\r\n        <td height=\"30\" align=\"left\" valign=\"middle\" bgcolor=\"#FFFFFF\" sty" +
                    "le=\"color: #000; border-right:1px solid #c7c3c7; font-family: Arial, Helvetica, " +
                    "sans-serif; font-size: 13px; text-align: center; font-weight: bold;\">");
            
            #line 78 "G:\GitHub\da-projects\3\CakeExtracter\CakeExtracter\Reports\SearchReportRuntimeTextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Currency(Line2stat.Cost)));
            
            #line default
            #line hidden
            this.Write("</td>\r\n        <td height=\"30\" align=\"left\" valign=\"middle\" bgcolor=\"#FFFFFF\" sty" +
                    "le=\"color: #000; border-right:1px solid #c7c3c7; font-family: Arial, Helvetica, " +
                    "sans-serif; font-size: 13px; text-align: center; font-weight: bold;\">");
            
            #line 79 "G:\GitHub\da-projects\3\CakeExtracter\CakeExtracter\Reports\SearchReportRuntimeTextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Integer(Line2stat.ROAS)));
            
            #line default
            #line hidden
            this.Write("%</td>\r\n        <td height=\"30\" align=\"left\" valign=\"middle\" bgcolor=\"#FFFFFF\" st" +
                    "yle=\"color: #000; border-right:1px solid #c7c3c7; font-family: Arial, Helvetica," +
                    " sans-serif; font-size: 13px; text-align: center; font-weight: bold;\">");
            
            #line 80 "G:\GitHub\da-projects\3\CakeExtracter\CakeExtracter\Reports\SearchReportRuntimeTextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Currency(Line2stat.Margin)));
            
            #line default
            #line hidden
            this.Write("</td>\r\n        <td height=\"30\" align=\"left\" valign=\"middle\" bgcolor=\"#FFFFFF\" sty" +
                    "le=\"color: #000; border-right:1px solid #c7c3c7; font-family: Arial, Helvetica, " +
                    "sans-serif; font-size: 13px; text-align: center; font-weight: bold;\">");
            
            #line 81 "G:\GitHub\da-projects\3\CakeExtracter\CakeExtracter\Reports\SearchReportRuntimeTextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Integer(Line2stat.Orders)));
            
            #line default
            #line hidden
            this.Write("</td>\r\n        <td height=\"30\" align=\"left\" valign=\"middle\" bgcolor=\"#FFFFFF\" sty" +
                    "le=\"color: #000; border-right:1px solid #c7c3c7; font-family: Arial, Helvetica, " +
                    "sans-serif; font-size: 13px; text-align: center; font-weight: bold;\">");
            
            #line 82 "G:\GitHub\da-projects\3\CakeExtracter\CakeExtracter\Reports\SearchReportRuntimeTextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Currency(Line2stat.CPO)));
            
            #line default
            #line hidden
            this.Write("</td>\r\n      ");
            
            #line 83 "G:\GitHub\da-projects\3\CakeExtracter\CakeExtracter\Reports\SearchReportRuntimeTextTemplate.tt"
 } else { 
            
            #line default
            #line hidden
            this.Write("        <td height=\"30\" align=\"left\" valign=\"middle\" bgcolor=\"#FFFFFF\" style=\"col" +
                    "or: #000; border-right:1px solid #c7c3c7; font-family: Arial, Helvetica, sans-se" +
                    "rif; font-size: 13px; text-align: center; font-weight: bold;\">");
            
            #line 84 "G:\GitHub\da-projects\3\CakeExtracter\CakeExtracter\Reports\SearchReportRuntimeTextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Integer(Line2stat.Clicks)));
            
            #line default
            #line hidden
            this.Write("</td>\r\n        <td height=\"30\" align=\"left\" valign=\"middle\" bgcolor=\"#FFFFFF\" sty" +
                    "le=\"color: #000; border-right:1px solid #c7c3c7; font-family: Arial, Helvetica, " +
                    "sans-serif; font-size: 13px; text-align: center; font-weight: bold;\">");
            
            #line 85 "G:\GitHub\da-projects\3\CakeExtracter\CakeExtracter\Reports\SearchReportRuntimeTextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Integer(Line2stat.Impressions)));
            
            #line default
            #line hidden
            this.Write("</td>\r\n        <td height=\"30\" align=\"left\" valign=\"middle\" bgcolor=\"#FFFFFF\" sty" +
                    "le=\"color: #000; border-right:1px solid #c7c3c7; font-family: Arial, Helvetica, " +
                    "sans-serif; font-size: 13px; text-align: center; font-weight: bold;\">");
            
            #line 86 "G:\GitHub\da-projects\3\CakeExtracter\CakeExtracter\Reports\SearchReportRuntimeTextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Decimal(Line2stat.CTR)));
            
            #line default
            #line hidden
            this.Write("%</td>\r\n        <td height=\"30\" align=\"left\" valign=\"middle\" bgcolor=\"#FFFFFF\" st" +
                    "yle=\"color: #000; border-right:1px solid #c7c3c7; font-family: Arial, Helvetica," +
                    " sans-serif; font-size: 13px; text-align: center; font-weight: bold;\">");
            
            #line 87 "G:\GitHub\da-projects\3\CakeExtracter\CakeExtracter\Reports\SearchReportRuntimeTextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Currency(Line2stat.Cost)));
            
            #line default
            #line hidden
            this.Write("</td>\r\n        <td height=\"30\" align=\"left\" valign=\"middle\" bgcolor=\"#FFFFFF\" sty" +
                    "le=\"color: #000; border-right:1px solid #c7c3c7; font-family: Arial, Helvetica, " +
                    "sans-serif; font-size: 13px; text-align: center; font-weight: bold;\">");
            
            #line 88 "G:\GitHub\da-projects\3\CakeExtracter\CakeExtracter\Reports\SearchReportRuntimeTextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Integer(Line2stat.Orders)));
            
            #line default
            #line hidden
            this.Write("</td>\r\n      ");
            
            #line 89 "G:\GitHub\da-projects\3\CakeExtracter\CakeExtracter\Reports\SearchReportRuntimeTextTemplate.tt"
 if (this.SearchProfile.ShowCalls) { 
            
            #line default
            #line hidden
            this.Write("        <td height=\"30\" align=\"left\" valign=\"middle\" bgcolor=\"#FFFFFF\" style=\"col" +
                    "or: #000; border-right:1px solid #c7c3c7; font-family: Arial, Helvetica, sans-se" +
                    "rif; font-size: 13px; text-align: center; font-weight: bold;\">");
            
            #line 90 "G:\GitHub\da-projects\3\CakeExtracter\CakeExtracter\Reports\SearchReportRuntimeTextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Integer(Line2stat.Calls)));
            
            #line default
            #line hidden
            this.Write("</td>\r\n        <td height=\"30\" align=\"left\" valign=\"middle\" bgcolor=\"#FFFFFF\" sty" +
                    "le=\"color: #000; border-right:1px solid #c7c3c7; font-family: Arial, Helvetica, " +
                    "sans-serif; font-size: 13px; text-align: center; font-weight: bold;\">");
            
            #line 91 "G:\GitHub\da-projects\3\CakeExtracter\CakeExtracter\Reports\SearchReportRuntimeTextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Integer(Line2stat.TotalLeads)));
            
            #line default
            #line hidden
            this.Write("</td>\r\n      ");
            
            #line 92 "G:\GitHub\da-projects\3\CakeExtracter\CakeExtracter\Reports\SearchReportRuntimeTextTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("        <td height=\"30\" align=\"left\" valign=\"middle\" bgcolor=\"#FFFFFF\" style=\"col" +
                    "or: #000; border-right:1px solid #c7c3c7; font-family: Arial, Helvetica, sans-se" +
                    "rif; font-size: 13px; text-align: center; font-weight: bold;\">");
            
            #line 93 "G:\GitHub\da-projects\3\CakeExtracter\CakeExtracter\Reports\SearchReportRuntimeTextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Currency(Line2stat.CPL)));
            
            #line default
            #line hidden
            this.Write("</td>\r\n      ");
            
            #line 94 "G:\GitHub\da-projects\3\CakeExtracter\CakeExtracter\Reports\SearchReportRuntimeTextTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("      </tr>\r\n");
            
            #line 96 "G:\GitHub\da-projects\3\CakeExtracter\CakeExtracter\Reports\SearchReportRuntimeTextTemplate.tt"
 } 
            
            #line default
            #line hidden
            
            #line 97 "G:\GitHub\da-projects\3\CakeExtracter\CakeExtracter\Reports\SearchReportRuntimeTextTemplate.tt"
 if (this.ChangeStat != null) { 
            
            #line default
            #line hidden
            this.Write("      <tr>\r\n        <td height=\"30\" align=\"left\" valign=\"middle\" bgcolor=\"#FFFFFF" +
                    "\" style=\"color: #000; border-right:1px solid #c7c3c7; font-family: Arial, Helvet" +
                    "ica, sans-serif; font-size: 13px; text-align: center; font-weight: bold;\">");
            
            #line 99 "G:\GitHub\da-projects\3\CakeExtracter\CakeExtracter\Reports\SearchReportRuntimeTextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.ChangeStat.Title));
            
            #line default
            #line hidden
            this.Write("</td>\r\n      ");
            
            #line 100 "G:\GitHub\da-projects\3\CakeExtracter\CakeExtracter\Reports\SearchReportRuntimeTextTemplate.tt"
 if (this.SearchProfile.ShowRevenue) { 
            
            #line default
            #line hidden
            this.Write("        <td height=\"30\" align=\"left\" valign=\"middle\" bgcolor=\"#FFFFFF\" style=\"col" +
                    "or: #");
            
            #line 101 "G:\GitHub\da-projects\3\CakeExtracter\CakeExtracter\Reports\SearchReportRuntimeTextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ChangeStat.Revenue > 0 ? "0F0" : (ChangeStat.Revenue < 0 ? "F00" : "000")));
            
            #line default
            #line hidden
            this.Write("; border-right:1px solid #c7c3c7; font-family: Arial, Helvetica, sans-serif; font" +
                    "-size: 13px; text-align: center; font-weight: bold;\">");
            
            #line 101 "G:\GitHub\da-projects\3\CakeExtracter\CakeExtracter\Reports\SearchReportRuntimeTextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Currency(ChangeStat.Revenue,true)));
            
            #line default
            #line hidden
            this.Write("</td>\r\n        <td height=\"30\" align=\"left\" valign=\"middle\" bgcolor=\"#FFFFFF\" sty" +
                    "le=\"color: #");
            
            #line 102 "G:\GitHub\da-projects\3\CakeExtracter\CakeExtracter\Reports\SearchReportRuntimeTextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ChangeStat.Cost > 0 ? "0F0" : (ChangeStat.Cost < 0 ? "F00" : "000")));
            
            #line default
            #line hidden
            this.Write("; border-right:1px solid #c7c3c7; font-family: Arial, Helvetica, sans-serif; font" +
                    "-size: 13px; text-align: center; font-weight: bold;\">");
            
            #line 102 "G:\GitHub\da-projects\3\CakeExtracter\CakeExtracter\Reports\SearchReportRuntimeTextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Currency(ChangeStat.Cost,true)));
            
            #line default
            #line hidden
            this.Write("</td>\r\n        <td height=\"30\" align=\"left\" valign=\"middle\" bgcolor=\"#FFFFFF\" sty" +
                    "le=\"color: #");
            
            #line 103 "G:\GitHub\da-projects\3\CakeExtracter\CakeExtracter\Reports\SearchReportRuntimeTextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ChangeStat.ROAS > 0 ? "0F0" : (ChangeStat.ROAS < 0 ? "F00" : "000")));
            
            #line default
            #line hidden
            this.Write("; border-right:1px solid #c7c3c7; font-family: Arial, Helvetica, sans-serif; font" +
                    "-size: 13px; text-align: center; font-weight: bold;\">");
            
            #line 103 "G:\GitHub\da-projects\3\CakeExtracter\CakeExtracter\Reports\SearchReportRuntimeTextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Integer(ChangeStat.ROAS,true)));
            
            #line default
            #line hidden
            
            #line 103 "G:\GitHub\da-projects\3\CakeExtracter\CakeExtracter\Reports\SearchReportRuntimeTextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ChangeStat.ROAS == 0 ? "" : "%"));
            
            #line default
            #line hidden
            this.Write("</td>\r\n        <td height=\"30\" align=\"left\" valign=\"middle\" bgcolor=\"#FFFFFF\" sty" +
                    "le=\"color: #");
            
            #line 104 "G:\GitHub\da-projects\3\CakeExtracter\CakeExtracter\Reports\SearchReportRuntimeTextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ChangeStat.Margin > 0 ? "0F0" : (ChangeStat.Margin < 0 ? "F00" : "000")));
            
            #line default
            #line hidden
            this.Write("; border-right:1px solid #c7c3c7; font-family: Arial, Helvetica, sans-serif; font" +
                    "-size: 13px; text-align: center; font-weight: bold;\">");
            
            #line 104 "G:\GitHub\da-projects\3\CakeExtracter\CakeExtracter\Reports\SearchReportRuntimeTextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Currency(ChangeStat.Margin,true)));
            
            #line default
            #line hidden
            this.Write("</td>\r\n        <td height=\"30\" align=\"left\" valign=\"middle\" bgcolor=\"#FFFFFF\" sty" +
                    "le=\"color: #");
            
            #line 105 "G:\GitHub\da-projects\3\CakeExtracter\CakeExtracter\Reports\SearchReportRuntimeTextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ChangeStat.Orders > 0 ? "0F0" : (ChangeStat.Orders < 0 ? "F00" : "000")));
            
            #line default
            #line hidden
            this.Write("; border-right:1px solid #c7c3c7; font-family: Arial, Helvetica, sans-serif; font" +
                    "-size: 13px; text-align: center; font-weight: bold;\">");
            
            #line 105 "G:\GitHub\da-projects\3\CakeExtracter\CakeExtracter\Reports\SearchReportRuntimeTextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Integer(ChangeStat.Orders,true)));
            
            #line default
            #line hidden
            this.Write("</td>\r\n        <td height=\"30\" align=\"left\" valign=\"middle\" bgcolor=\"#FFFFFF\" sty" +
                    "le=\"color: #");
            
            #line 106 "G:\GitHub\da-projects\3\CakeExtracter\CakeExtracter\Reports\SearchReportRuntimeTextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ChangeStat.CPO > 0 ? "0F0" : (ChangeStat.CPO < 0 ? "F00" : "000")));
            
            #line default
            #line hidden
            this.Write("; border-right:1px solid #c7c3c7; font-family: Arial, Helvetica, sans-serif; font" +
                    "-size: 13px; text-align: center; font-weight: bold;\">");
            
            #line 106 "G:\GitHub\da-projects\3\CakeExtracter\CakeExtracter\Reports\SearchReportRuntimeTextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Currency(ChangeStat.CPO,true)));
            
            #line default
            #line hidden
            this.Write("</td>\r\n      ");
            
            #line 107 "G:\GitHub\da-projects\3\CakeExtracter\CakeExtracter\Reports\SearchReportRuntimeTextTemplate.tt"
 } else { 
            
            #line default
            #line hidden
            this.Write("        <td height=\"30\" align=\"left\" valign=\"middle\" bgcolor=\"#FFFFFF\" style=\"col" +
                    "or: #");
            
            #line 108 "G:\GitHub\da-projects\3\CakeExtracter\CakeExtracter\Reports\SearchReportRuntimeTextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ChangeStat.Clicks > 0 ? "0F0" : (ChangeStat.Clicks < 0 ? "F00" : "000")));
            
            #line default
            #line hidden
            this.Write("; border-right:1px solid #c7c3c7; font-family: Arial, Helvetica, sans-serif; font" +
                    "-size: 13px; text-align: center; font-weight: bold;\">");
            
            #line 108 "G:\GitHub\da-projects\3\CakeExtracter\CakeExtracter\Reports\SearchReportRuntimeTextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Integer(ChangeStat.Clicks,true)));
            
            #line default
            #line hidden
            this.Write("</td>\r\n        <td height=\"30\" align=\"left\" valign=\"middle\" bgcolor=\"#FFFFFF\" sty" +
                    "le=\"color: #");
            
            #line 109 "G:\GitHub\da-projects\3\CakeExtracter\CakeExtracter\Reports\SearchReportRuntimeTextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ChangeStat.Impressions > 0 ? "0F0" : (ChangeStat.Impressions < 0 ? "F00" : "000")));
            
            #line default
            #line hidden
            this.Write("; border-right:1px solid #c7c3c7; font-family: Arial, Helvetica, sans-serif; font" +
                    "-size: 13px; text-align: center; font-weight: bold;\">");
            
            #line 109 "G:\GitHub\da-projects\3\CakeExtracter\CakeExtracter\Reports\SearchReportRuntimeTextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Integer(ChangeStat.Impressions,true)));
            
            #line default
            #line hidden
            this.Write("</td>\r\n        <td height=\"30\" align=\"left\" valign=\"middle\" bgcolor=\"#FFFFFF\" sty" +
                    "le=\"color: #");
            
            #line 110 "G:\GitHub\da-projects\3\CakeExtracter\CakeExtracter\Reports\SearchReportRuntimeTextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ChangeStat.CTR > 0 ? "0F0" : (ChangeStat.CTR < 0 ? "F00" : "000")));
            
            #line default
            #line hidden
            this.Write("; border-right:1px solid #c7c3c7; font-family: Arial, Helvetica, sans-serif; font" +
                    "-size: 13px; text-align: center; font-weight: bold;\">");
            
            #line 110 "G:\GitHub\da-projects\3\CakeExtracter\CakeExtracter\Reports\SearchReportRuntimeTextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Decimal(ChangeStat.CTR,true)));
            
            #line default
            #line hidden
            
            #line 110 "G:\GitHub\da-projects\3\CakeExtracter\CakeExtracter\Reports\SearchReportRuntimeTextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ChangeStat.CTR == 0 ? "" : "%"));
            
            #line default
            #line hidden
            this.Write("</td>\r\n        <td height=\"30\" align=\"left\" valign=\"middle\" bgcolor=\"#FFFFFF\" sty" +
                    "le=\"color: #");
            
            #line 111 "G:\GitHub\da-projects\3\CakeExtracter\CakeExtracter\Reports\SearchReportRuntimeTextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ChangeStat.Cost > 0 ? "0F0" : (ChangeStat.Cost < 0 ? "F00" : "000")));
            
            #line default
            #line hidden
            this.Write("; border-right:1px solid #c7c3c7; font-family: Arial, Helvetica, sans-serif; font" +
                    "-size: 13px; text-align: center; font-weight: bold;\">");
            
            #line 111 "G:\GitHub\da-projects\3\CakeExtracter\CakeExtracter\Reports\SearchReportRuntimeTextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Currency(ChangeStat.Cost,true)));
            
            #line default
            #line hidden
            this.Write("</td>\r\n        <td height=\"30\" align=\"left\" valign=\"middle\" bgcolor=\"#FFFFFF\" sty" +
                    "le=\"color: #");
            
            #line 112 "G:\GitHub\da-projects\3\CakeExtracter\CakeExtracter\Reports\SearchReportRuntimeTextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ChangeStat.Orders > 0 ? "0F0" : (ChangeStat.Orders < 0 ? "F00" : "000")));
            
            #line default
            #line hidden
            this.Write("; border-right:1px solid #c7c3c7; font-family: Arial, Helvetica, sans-serif; font" +
                    "-size: 13px; text-align: center; font-weight: bold;\">");
            
            #line 112 "G:\GitHub\da-projects\3\CakeExtracter\CakeExtracter\Reports\SearchReportRuntimeTextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Integer(ChangeStat.Orders,true)));
            
            #line default
            #line hidden
            this.Write("</td>\r\n      ");
            
            #line 113 "G:\GitHub\da-projects\3\CakeExtracter\CakeExtracter\Reports\SearchReportRuntimeTextTemplate.tt"
 if (this.SearchProfile.ShowCalls) { 
            
            #line default
            #line hidden
            this.Write("        <td height=\"30\" align=\"left\" valign=\"middle\" bgcolor=\"#FFFFFF\" style=\"col" +
                    "or: #");
            
            #line 114 "G:\GitHub\da-projects\3\CakeExtracter\CakeExtracter\Reports\SearchReportRuntimeTextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ChangeStat.Calls > 0 ? "0F0" : (ChangeStat.Calls < 0 ? "F00" : "000")));
            
            #line default
            #line hidden
            this.Write("; border-right:1px solid #c7c3c7; font-family: Arial, Helvetica, sans-serif; font" +
                    "-size: 13px; text-align: center; font-weight: bold;\">");
            
            #line 114 "G:\GitHub\da-projects\3\CakeExtracter\CakeExtracter\Reports\SearchReportRuntimeTextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Integer(ChangeStat.Calls,true)));
            
            #line default
            #line hidden
            this.Write("</td>\r\n        <td height=\"30\" align=\"left\" valign=\"middle\" bgcolor=\"#FFFFFF\" sty" +
                    "le=\"color: #");
            
            #line 115 "G:\GitHub\da-projects\3\CakeExtracter\CakeExtracter\Reports\SearchReportRuntimeTextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ChangeStat.TotalLeads > 0 ? "0F0" : (ChangeStat.TotalLeads < 0 ? "F00" : "000")));
            
            #line default
            #line hidden
            this.Write("; border-right:1px solid #c7c3c7; font-family: Arial, Helvetica, sans-serif; font" +
                    "-size: 13px; text-align: center; font-weight: bold;\">");
            
            #line 115 "G:\GitHub\da-projects\3\CakeExtracter\CakeExtracter\Reports\SearchReportRuntimeTextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Integer(ChangeStat.TotalLeads,true)));
            
            #line default
            #line hidden
            this.Write("</td>\r\n      ");
            
            #line 116 "G:\GitHub\da-projects\3\CakeExtracter\CakeExtracter\Reports\SearchReportRuntimeTextTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("        <td height=\"30\" align=\"left\" valign=\"middle\" bgcolor=\"#FFFFFF\" style=\"col" +
                    "or: #");
            
            #line 117 "G:\GitHub\da-projects\3\CakeExtracter\CakeExtracter\Reports\SearchReportRuntimeTextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ChangeStat.CPL > 0 ? "0F0" : (ChangeStat.CPL < 0 ? "F00" : "000")));
            
            #line default
            #line hidden
            this.Write("; border-right:1px solid #c7c3c7; font-family: Arial, Helvetica, sans-serif; font" +
                    "-size: 13px; text-align: center; font-weight: bold;\">");
            
            #line 117 "G:\GitHub\da-projects\3\CakeExtracter\CakeExtracter\Reports\SearchReportRuntimeTextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Currency(ChangeStat.CPL,true)));
            
            #line default
            #line hidden
            this.Write("</td>\r\n      ");
            
            #line 118 "G:\GitHub\da-projects\3\CakeExtracter\CakeExtracter\Reports\SearchReportRuntimeTextTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("      </tr>\r\n");
            
            #line 120 "G:\GitHub\da-projects\3\CakeExtracter\CakeExtracter\Reports\SearchReportRuntimeTextTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write(@"
    </table>
</td>
  </tr>
  <tr>
    <td width=""13"" align=""left"" valign=""top"">&nbsp;</td>
    <td colspan=""2"" align=""left"" valign=""top"" ><span style=""font-family: Arial, Helvetica, sans-serif; font-size: 14px;"" ><br>The Direct Agents Client Portal provides access to real-time reports showing campaign effectiveness and spend across all search channels. You can easily view a breakdown by individual campaign and visualize key metrics your campaign performance with interactive charts. <a href=""http://portal.directagents.com/"" style=""color:#37A5F2;""><strong>View reports now</strong></a></span></td>
    <td width=""13"" align=""left"" valign=""top"">&nbsp;</td>
  </tr>
  <tr>
    <td width=""13"" align=""left"" valign=""top"">&nbsp;</td>
    <td colspan=""2"" align=""left"" valign=""top"" ><span style=""font-family: Arial, Helvetica, sans-serif; font-size: 14px;"" ><br>Questions? Contact your account manager, ");
            
            #line 132 "G:\GitHub\da-projects\3\CakeExtracter\CakeExtracter\Reports\SearchReportRuntimeTextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.AcctMgrName));
            
            #line default
            #line hidden
            this.Write(": <a href=\"mailto:");
            
            #line 132 "G:\GitHub\da-projects\3\CakeExtracter\CakeExtracter\Reports\SearchReportRuntimeTextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.AcctMgrEmail));
            
            #line default
            #line hidden
            this.Write("\" style=\"color:#37A5F2;\">");
            
            #line 132 "G:\GitHub\da-projects\3\CakeExtracter\CakeExtracter\Reports\SearchReportRuntimeTextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.AcctMgrEmail));
            
            #line default
            #line hidden
            this.Write(@"</a></span></td>
    <td width=""13"" align=""left"" valign=""top"">&nbsp;</td>
  </tr>
  <tr>
    <td height=""13"" colspan=""4"" align=""left"" valign=""top"">&nbsp;</td>
  </tr>
  <tr>
    <td width=""13"" align=""left"" valign=""top"">&nbsp;</td>
    <td height=""80"" colspan=""2"" align=""left"" valign=""middle""><table width=""593"" border=""0"" align=""left"" cellpadding=""0"" cellspacing=""0"">
        <tr>
          <td width=""68"" align=""center"" valign=""top""><img src=""https://portal.directagents.com/Images/icon_reports.gif"" alt="""" style=""width:60%; height:auto;"" /></td>
          <td width=""450"" align=""left"" valign=""middle""><span style=""font-family: Arial, Helvetica, sans-serif; font-size: 14px;""><strong>Top Tip: You can export your data from your reports in CSV format. </strong><a href=""http://portal.directagents.com/"" style=""color:#37A5F2;""><strong>Log in</strong></a></span></td>
        </tr>
    </table></td>
    <td width=""13"" align=""right"" valign=""top"">&nbsp;</td>
  </tr>
</table>
</td>
</tr>
</table>
");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "12.0.0.0")]
    public class SearchReportRuntimeTextTemplateBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
