// <auto-generated />
namespace ClientPortal.Data.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Mig_AdDailySummary : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Mig_AdDailySummary));
        
        string IMigrationMetadata.Id
        {
            get { return "201408121512151_Mig_AdDailySummary"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
