// <auto-generated />
namespace ClientPortal.Data.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Mig_ModDbmDailySummaries : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Mig_ModDbmDailySummaries));
        
        string IMigrationMetadata.Id
        {
            get { return "201409092206193_Mig_ModDbmDailySummaries"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
