// <auto-generated />
namespace ClientPortal.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Mig_DBMConversionFields : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Mig_DBMConversionFields));
        
        string IMigrationMetadata.Id
        {
            get { return "201504231735446_Mig_DBMConversionFields"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
