// <auto-generated />
namespace DirectAgents.Domain.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class OfferBudget : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(OfferBudget));
        
        string IMigrationMetadata.Id
        {
            get { return "201406042147505_OfferBudget"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
