// <auto-generated />
namespace DirectAgents.Domain.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class RmOfferInfo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RmOfferInfo));
        
        string IMigrationMetadata.Id
        {
            get { return "201406051452281_RmOfferInfo"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
