//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DirectAgents.Domain.Entities.Wiki
{
    using System;
    using System.Collections.Generic;
    
    public partial class Campaign
    {
        public Campaign()
        {
            this.AccountManagers = new HashSet<Person>();
            this.AdManagers = new HashSet<Person>();
            this.Countries = new HashSet<Country>();
            this.TrafficTypes = new HashSet<TrafficType>();
        }
    
        public int Pid { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string PayableAction { get; set; }
        public string Link { get; set; }
        public string CostCurrency { get; set; }
        public decimal Cost { get; set; }
        public string RevenueCurrency { get; set; }
        public decimal Revenue { get; set; }
        public string ImportantDetails { get; set; }
        public string CampaignCap { get; set; }
        public string ScrubPolicy { get; set; }
        public string EomNotes { get; set; }
        public string ImageUrl { get; set; }
        public Nullable<int> Vertical_VerticalId { get; set; }
        public string Restrictions { get; set; }
        public string Budget { get; set; }
        public string PassedInfo { get; set; }
        public Nullable<int> StatusId { get; set; }
        public bool Hidden { get; set; }
        public string DefaultPriceFormat { get; set; }
        public bool RevenueIsPercentage { get; set; }
        public string MobileLP { get; set; }
    
        public virtual Status Status { get; set; }
        public virtual Vertical Vertical { get; set; }
        public virtual ICollection<Person> AccountManagers { get; set; }
        public virtual ICollection<Person> AdManagers { get; set; }
        public virtual ICollection<Country> Countries { get; set; }
        public virtual ICollection<TrafficType> TrafficTypes { get; set; }
    }
}
