//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DirectAgents.Domain.Entities.Wiki
{
    using System;
    using System.Collections.Generic;
    
    public partial class Conversion
    {
        public int conversion_id { get; set; }
        public int visitor_id { get; set; }
        public int request_session_id { get; set; }
        public int click_id { get; set; }
        public System.DateTime conversion_date { get; set; }
        public int affiliate_affiliate_id { get; set; }
        public string affiliate_affiliate_name { get; set; }
        public int advertiser_advertiser_id { get; set; }
        public string advertiser_advertiser_name { get; set; }
        public int offer_offer_id { get; set; }
        public string offer_offer_name { get; set; }
        public int creative_creative_id { get; set; }
        public string creative_creative_name { get; set; }
        public string sub_id_1 { get; set; }
        public string sub_id_2 { get; set; }
        public string sub_id_3 { get; set; }
        public string conversion_type { get; set; }
        public int paid_currency_id { get; set; }
        public decimal paid_amount { get; set; }
        public string paid_formatted_amount { get; set; }
        public int received_currency_id { get; set; }
        public decimal received_amount { get; set; }
        public string received_formatted_amount { get; set; }
        public bool pixel_dropped { get; set; }
        public bool suppressed { get; set; }
        public bool returned { get; set; }
        public bool test { get; set; }
        public string transaction_id { get; set; }
        public string ip_address { get; set; }
        public string referrer_url { get; set; }
        public string note { get; set; }
    }
}
