//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DirectAgents.Domain.Entities.Wiki
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public Person()
        {
            this.AccountManagerCampaigns = new HashSet<Campaign>();
            this.AdManagerCampaigns = new HashSet<Campaign>();
        }
    
        public int PersonId { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Campaign> AccountManagerCampaigns { get; set; }
        public virtual ICollection<Campaign> AdManagerCampaigns { get; set; }
    }
}
